'use strict'
var __defProp = Object.defineProperty
var __getOwnPropDesc = Object.getOwnPropertyDescriptor
var __getOwnPropNames = Object.getOwnPropertyNames
var __hasOwnProp = Object.prototype.hasOwnProperty
var __export = (target, all) => {
  for (var name in all) __defProp(target, name, { get: all[name], enumerable: true })
}
var __copyProps = (to, from, except, desc) => {
  if ((from && typeof from === 'object') || typeof from === 'function') {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable })
  }
  return to
}
var __toCommonJS = (mod) => __copyProps(__defProp({}, '__esModule', { value: true }), mod)
var dictionary_exports = {}
__export(dictionary_exports, {
  dictionaries: () => dictionaries,
  dictionaryResources: () => dictionaryResources,
  idDictionaryMap: () => idDictionaryMap,
})
module.exports = __toCommonJS(dictionary_exports)
var import_utils = require('@/utils')
const generalEnglish = [
  {
    id: 'coca_20000',
    name: 'COCA20000t\u1EEB',
    description: 'COCA20000t\u1EEB',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/coca20000.json',
    length: 20199,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words1',
    name: 'Essential Words',
    description: '4000 Essential English Words meaning',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/4000_Essential_English_Words-meaning.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words2',
    name: 'Essential Words',
    description: '4000 Essential English Words sentence',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/4000_Essential_English_Words-sentence.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'longman_communication_3000_words',
    name: 'Longman Communication 3000',
    description: 'Most frequent words in both spoken and written English',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Longman_Communication_3000.json',
    length: 3168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_2000_English_Words',
    name: 'Top 2000 words',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/top2000words.json',
    length: 1867,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1500_nouns_Words',
    name: 'Top 1500 Nouns',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top1500NounWords.json',
    length: 1525,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1000_verb_Words',
    name: 'Top 1000 Verbs',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top1000VerbWords.json',
    length: 1011,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_500_Adj_Words',
    name: 'Top 500 adj.',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top500AdjectiveWords.json',
    length: 527,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_250_Adv_Words',
    name: 'Top 250 adv.',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top250AdverbWords.json',
    length: 255,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_60_Pronouns',
    name: 'Top 60 pron.',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top60Pronouns.json',
    length: 59,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_50_Prepositions',
    name: 'Top 50 prep.',
    description: 'with highest frequency',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top50Prepositions.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'suffix word',
    name: 'suffix word',
    description: 'common suffix',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/suffix_word.json',
    length: 126,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'word roots1',
    name: 'word roots1',
    description: 'common roots',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/word_roots1.json',
    length: 369,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford5000t\u1EEB',
    description: 'Oxford5000t\u1EEB',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Merriam_Webster_sVocabularyBuilder',
    name: 'c\u1EE7a WebsterT\u1EEB \u0111i\u1EC3n g\u1ED1c t\u1EEB',
    description: 'c\u1EE7a WebsterT\u1EEB \u0111i\u1EC3n g\u1ED1c t\u1EEB',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Merriam_Webster_sVocabularyBuilder.json',
    length: 1191,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEFL_ZhangHongYan',
    name: 'T\u1EEB v\u1EF1ng TOEFL (ZhangHongYan)',
    description: 'T\u1EEB v\u1EF1ng TOEFL (ZhangHongYan) - Theo ch\u1EE7 \u0111\u1EC1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_ZhangHongYan.json',
    length: 4032,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'roger',
    name: "Roger's Words",
    description: 'D\xF9ng trong h\u1ECDc t\u1EADp & c\xF4ng vi\u1EC7cTi\u1EBFng Anh',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Ngo\u1EA1i kho\xE1'],
    url: '/dicts/RogersWords.json',
    length: 4174,
    language: 'en',
    languageCategory: 'en',
  },
]
const internationalExam = [
  {
    id: 'pet-2024',
    name: 'PET-2024',
    description: 'CambridgeTi\u1EBFng Anh - 2024',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PET'],
    url: '/dicts/pet-vacabulary-list-2024.json',
    length: 1871,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gmat',
    name: 'GMAT',
    description: 'GMAT t\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GMAT'],
    url: '/dicts/GMAT_3_T.json',
    length: 3047,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre',
    name: 'GRE',
    description: 'GRE t\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE_3_T.json',
    length: 6515,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre1500',
    name: 'GREt\u1EADp trung1500t\u1EEB-fenanh trai',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao GRE & TEM8',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE_1500.json',
    length: 1533,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre3000',
    name: 'GRE3000',
    description: 'T\u1EEB v\u1EF1ng GRE3000',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE3000_3_T.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE-computer-based-test',
    name: 'GRET\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    description: 'GRET\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE-computer-based-test.json',
    length: 1451,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ZaiYaoNiMing_GRE3000',
    name: 'GRE3000 T\xE1i xu\u1EA5t',
    description: 'GRE3000 T\xE1i xu\u1EA5tt\u1EEB v\u1EF1ng-c\xF3t\u1EEBphi\xEAn b\u1EA3n m\u1EDBi c\u1EE7a t\xECnh d\u1EE5c',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/ZaiYaoNiMing_GRE3000.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_equivalent',
    name: 'T\u1EEB \u0111\u1ED3ng ngh\u0129a GRE',
    description: 'T\u1EEB \u0111\u1ED3ng ngh\u0129a GRE',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE_equivalent.json',
    length: 827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_ciyileiji',
    name: 'GREt\u1EEBTheo ch\u1EE7 \u0111\u1EC1',
    description: 'GREt\u1EEBTheo ch\u1EE7 \u0111\u1EC1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/gre-ciyileiji.json',
    length: 8785,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'biomedical-terms',
    name: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Y sinh',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Y sinh',
    category: 'T\u1EEB v\u1EF1ng chuy\xEAn ng\xE0nh',
    tags: ['Sinh h\u1ECDc'],
    url: '/dicts/BIOmedical.json',
    length: 560,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS_tinglichangjing',
    name: 'Ch\u1EE7 \u0111\u1EC1 Nghe IELTSt\u1EEB v\u1EF1ng',
    description: 'Ch\u1EE7 \u0111\u1EC1 Nghe IELTSt\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_tinglichangjing.json',
    length: 1204,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_disorder',
    name: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Ng\u1EABu nhi\xEAn)',
    description: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Ng\u1EABu nhi\xEAn)',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_disorder.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_order',
    name: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Theo th\u1EE9 t\u1EF1)',
    description: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Theo th\u1EE9 t\u1EF1)',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_order.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts',
    name: 'IELTS',
    description: 'IELTSt\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_3_T.json',
    length: 3575,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'heqiong',
    name: 'T\u1EEB v\u1EF1ng IELTS Listening (heQiong)t\u1EEB v\u1EF1ng',
    description: '\u0110\u1EC1 t\u1ED5ng h\u1EE3p',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/HeQiong_IELTS.json',
    length: 2529,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang3',
    name: 'IELTS Wang C3',
    description: 'Danh t\u1EEB ri\xEAng IELTS Listeningt\u1EEB\u0111\u1EC1 thi',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_3.json',
    length: 1135,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang4',
    name: 'IELTS Wang C4',
    description: 'T\xEDnh t\u1EEB/Ph\xF3 t\u1EEB IELTS Listeningt\u1EEBph\xF3t\u1EEB\u0111\u1EC1 thi',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_4.json',
    length: 346,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang5',
    name: 'IELTS Wang C5',
    description: 'Luy\u1EC7n t\u1EADp n\u1ED1i \xE2m v\xE0 nu\u1ED1t \xE2m',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_5.json',
    length: 1569,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang11',
    name: 'IELTS Wang C11',
    description: '\u0110\u1EC1 t\u1ED5ng h\u1EE3p',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_11.json',
    length: 1738,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'DuckCircle_IELTS',
    name: 'T\u1EEB v\u1EF1ng IELTS c\u1ED1t l\xF5i (Yaquan)t\u1EEB',
    description: 'T\u1EEB v\u1EF1ng IELTS c\u1ED1t l\xF5i (Yaquan)t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/DuckCircle_IELTS.json',
    length: 2644,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSVocabularyBible',
    name: 'IELTSt\u1EEBHuizhen Jing',
    description: 'IELTSt\u1EEBHuizhen Jing',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTSVocabularyBible.json',
    length: 3673,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-807',
    name: 'IELTS wanglu 807',
    description: 'IELTS wanglu 807',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-807.json',
    length: 4340,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-high',
    name: 'IELTS real t\u1EEB v\u1EF1ng t\u1EA7n su\u1EA5t cao',
    description: 'IELTS real t\u1EEB v\u1EF1ng\uFF08t\u1EA7n su\u1EA5t caot\u1EEB v\u1EF1ng\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-high.json',
    length: 524,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-5',
    name: 'IELTS real t\u1EEB v\u1EF1ng 5',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF085T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-5.json',
    length: 183,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-4',
    name: 'IELTS real t\u1EEB v\u1EF1ng 4',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF084T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-4.json',
    length: 201,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-3',
    name: 'IELTS real t\u1EEB v\u1EF1ng 3',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF083T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-3.json',
    length: 256,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-2',
    name: 'IELTS real t\u1EEB v\u1EF1ng 2',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF082T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-2.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-1',
    name: 'IELTS real t\u1EEB v\u1EF1ng 1',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF081T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-1.json',
    length: 737,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS9988wangyong',
    name: 'IELTS9988wangyong',
    description: 'IELTS9988wangyong',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS9988wangyong.json',
    length: 3698,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSKingLu807',
    name: 'wanglu807IELTSt\u1EEBHu\u1EC7 Th\xEDnhKH\xD4NG.2phi\xEAn b\u1EA3n',
    description: 'wanglu807IELTSt\u1EEBHu\u1EC7 Th\xEDnhKH\xD4NG.2phi\xEAn b\u1EA3n',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTSKingLu807.json',
    length: 1916,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSXDF7000',
    name: '100N\xF3i xong c\xE2u7000IELTSt\u1EEB',
    description: 'xdf 100N\xF3i xong c\xE2u7000IELTSt\u1EEB t\u1EEBTuy\xEAn b\u1ED1 trao \u0111\u1ED5i',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_XDF_7000.json',
    length: 5567,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-oral-900',
    name: 'N\xF3i IELTS 900 betaphi\xEAn b\u1EA3n',
    description:
      'N\xF3i IELTS 900 c\xE2u, nhu c\u1EA7uhi\u1EC7n h\u1EEFu qwerty c\xE0i \u0111\u1EB7t\xC2m trung nh\u1ECFTi\u1EBFng Anhph\xF4ng ch\u1EEF',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-oral-900.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task1',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day1',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task1.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task2',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day2',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day2',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task2.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task3',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day3',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day3',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task3.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task4',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day4',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day4',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task4.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task5',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day5',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day5',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task5.json',
    length: 38,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task6',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day6',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day6',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task6.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task7',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day7',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day7',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task7.json',
    length: 39,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task8',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day8',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day8',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task8.json',
    length: 32,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task9',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day9',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day9',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task9.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task10',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day10',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day10',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task10.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task11',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day11',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day11',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task11.json',
    length: 36,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task12',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day12',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day12',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task12.json',
    length: 45,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task13',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day13',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day13',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task13.json',
    length: 49,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task14',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day14',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day14',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task14.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task15',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day15',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day15',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task15.json',
    length: 29,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task16',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day16',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day16',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task16.json',
    length: 42,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task17',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day17',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day17',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task17.json',
    length: 22,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task18',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day18',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day18',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task18.json',
    length: 37,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task19',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day19',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day19',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task19.json',
    length: 26,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-1',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day1',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day1.json',
    length: 74,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-2',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day2',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day2',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day2.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-3',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day3',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day3',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day3.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-4',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day4',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day4',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day4.json',
    length: 73,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-5',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day5',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day5',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day5.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-6',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day6',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day6',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day6.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-7',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day7',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day7',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day7.json',
    length: 75,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-8',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day8',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day8',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day8.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-9',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day9',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day9',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day9.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-10',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day10',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day10',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day10.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-11',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day11',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day11',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day11.json',
    length: 52,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-12',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day12',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day12',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day12.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-13',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day13',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day13',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day13.json',
    length: 78,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-14',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day14',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day14',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day14.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-15',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day15',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day15',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day15.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-16',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day16',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day16',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day16.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-17',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day17',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day17',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day17.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-18',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day18',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day18',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day18.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ket',
    name: 'KET',
    description: 'KET 2021t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['KET'],
    url: './dicts/ket2021.json',
    length: 1147,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'sat',
    name: 'SAT',
    description: 'Hoa K\u1EF3 SAT T\u1EEB v\u1EF1ng thi',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['SAT'],
    url: '/dicts/SAT_3_T.json',
    length: 4464,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SATen',
    name: 'SAT en-en',
    description: 'SATYingying',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['SAT'],
    url: '/dicts/SATen.json',
    length: 2681,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'toefl',
    name: 'TOEFL',
    description: '\u0110\u1EC1 thi TOEFL ph\u1ED5 bi\u1EBFnt\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_3_T.json',
    length: 4264,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'bec2',
    name: 'Ti\u1EBFng Anh th\u01B0\u01A1ng m\u1EA1i',
    description: 'Ti\u1EBFng Anh th\u01B0\u01A1ng m\u1EA1ichungt\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['BEC'],
    url: '/dicts/BEC_2_T.json',
    length: 2753,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'bec3',
    name: 'BEC',
    description: 'BECC\xE1c k\u1EF3 thi chungt\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['BEC'],
    url: '/dicts/BEC_3_T.json',
    length: 2825,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_junior',
    name: 'PTE C\u0103n c\u1EE9t\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_junior.json',
    length: 2651,
    language: 'en',
    languageCategory: 'en',
  },
  // {
  //   id: 'PTE_WFDgaopinci.json',
  //   name: 'PTE WFDtần suất caotừ vựng',
  //   description: 'WFDtần suất caotừchìm từ cao xuống thấp，sự thành thạo tối thiểu350cá nhân',
  //   category: 'Kỳ thi Quốc tế',
  //   tags: ['PTE'],
  //   url: '/dicts/PTE_WFDgaopinci.json',
  //   length: 1175,
  //   language: 'en',
  //   languageCategory: 'en',
  // },
  {
    id: 'PTE_senior',
    name: 'PTE Tr\xECnh \u0111\u1ED9 caot\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_senior.json',
    length: 3170,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_R_junior',
    name: '\u0111\u1ECDc FIB C\u01A1 h\u1ECDc c\u01A1 b\u1EA3nt\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_R_junior.json',
    length: 941,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_R_senior',
    name: '\u0111\u1ECDc FIB M\xE1y m\xF3c ti\xEAn ti\u1EBFnt\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_R_senior.json',
    length: 1272,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_WFD',
    name: 'WFD T\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_WFD.json',
    length: 1212,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_L',
    name: 'th\xEDnh gi\xE1c FIB T\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_L.json',
    length: 646,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Basic_apeuni',
    name: 'PTE C\u0103n c\u1EE9t\u1EEB v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Basic_apeuni.json',
    length: 2652,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Advanced_apeuni.json',
    name: 'PTE Tr\xECnh \u0111\u1ED9 caot\u1EEB v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Advanced_apeuni.json',
    length: 3169,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Read_apeuni.json',
    name: 'PTE \u0111\u1ECDcFIBT\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Read_apeuni.json',
    length: 630,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Listening_apeuni.json',
    name: 'PTE th\xEDnh gi\xE1cFIBT\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Listening_apeuni.json',
    length: 674,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEIC',
    name: 'TOEIC t\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEIC'],
    url: '/dicts/TOEIC.json',
    length: 1694,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_B1',
    name: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB1',
    description: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_B1.json',
    length: 801,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_B2',
    name: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB2',
    description: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB2',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_B2.json',
    length: 1423,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_C1',
    name: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngC1',
    description: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngC1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_C1.json',
    length: 1314,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford3000',
    name: 'Oxford3000t\u1EEB',
    description: 'Oxford3000t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['Phi\xEAn b\u1EA3n Oxford'],
    url: '/dicts/Oxford3000.json',
    length: 1342,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford5000t\u1EEB',
    description: 'Oxford5000t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['Phi\xEAn b\u1EA3n Oxford'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'voa',
    name: 'T\u1EEB v\u1EF1ng VOA C\u01A1 b\u1EA3n',
    description: 'T\u1EEB v\u1EF1ng VOA C\u01A1 b\u1EA3n',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['Kh\xE1c'],
    url: '/dicts/voa.json',
    length: 1505,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Common-Phrases-PTE-Unofficial',
    name: 'C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng PTE',
    description: 'PTE C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/Common-Phrases-PTE-Unofficial.json',
    length: 274,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Common-Phrases-FCE-Unofficial',
    name: 'C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng FCE',
    description: 'FCE C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['FCE'],
    url: '/dicts/Common-Phrases-FCE-Unofficial.json',
    length: 438,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Categorized_TOEFL_Vocabulary_by_Zhanghongyan',
    name: 'T\u1EEB v\u1EF1ng ph\xE2n lo\u1EA1i',
    description: 'T\u1EEB v\u1EF1ng TOEFL Theo ch\u1EE7 \u0111\u1EC1 (ZhangHongYan 2021)',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEFL'],
    url: '/dicts/Categorized_TOEFL_Vocabulary_by_Zhanghongyan.json',
    length: 4123,
    language: 'en',
    languageCategory: 'en',
  },
]
const childrenEnglish = [
  {
    id: 'nce1',
    name: 'New Concept English 1',
    description: 'New Concept English Quy\u1EC3n 1',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_1.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce2',
    name: 'New Concept English 2',
    description: 'New Concept English Quy\u1EC3n 2',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_2.json',
    length: 858,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce3',
    name: 'New Concept English 3',
    description: 'New Concept English Quy\u1EC3n 3',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_3.json',
    length: 1052,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce4',
    name: 'New Concept English 4',
    description: 'New Concept English Quy\u1EC3n 4',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_4.json',
    length: 784,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-1',
    name: 'New Concept English 1 (M\u1EDBi)',
    description: 'New Concept English Quy\u1EC3n 1 (B\u1EA3n m\u1EDBi)',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-1.json',
    length: 908,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-2',
    name: 'New Concept English 2 (M\u1EDBi)',
    description: 'New Concept English Quy\u1EC3n 2 (B\u1EA3n m\u1EDBi)',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-2.json',
    length: 862,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-3',
    name: 'New Concept English 3 (M\u1EDBi)',
    description: 'New Concept English Quy\u1EC3n 3 (B\u1EA3n m\u1EDBi)',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-3.json',
    length: 1062,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-4',
    name: 'New Concept English 4 (M\u1EDBi)',
    description: 'New Concept English Quy\u1EC3n 4 (B\u1EA3n m\u1EDBi)',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-4.json',
    length: 793,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel1',
    name: 'EF-LEVEL-1',
    description: 'EF C\u1EA5p \u0111\u1ED9 1',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_1.json',
    length: 297,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel2',
    name: 'EF-LEVEL-2',
    description: 'EF C\u1EA5p \u0111\u1ED9 2',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_2.json',
    length: 353,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel3',
    name: 'EF-LEVEL-3',
    description: 'EF C\u1EA5p \u0111\u1ED9 3',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_3.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel4',
    name: 'EF-LEVEL-4',
    description: 'EF C\u1EA5p \u0111\u1ED9 4',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_4.json',
    length: 178,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel5',
    name: 'EF-LEVEL-5',
    description: 'EF C\u1EA5p \u0111\u1ED9 5',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_5.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel6',
    name: 'EF-LEVEL-6',
    description: 'EF C\u1EA5p \u0111\u1ED9 6',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_6.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel7',
    name: 'EF-LEVEL-7',
    description: 'EF C\u1EA5p \u0111\u1ED9 7',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_7.json',
    length: 171,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel8',
    name: 'EF-LEVEL-8',
    description: 'EF C\u1EA5p \u0111\u1ED9 8',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_8.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel9',
    name: 'EF-LEVEL-9',
    description: 'EF C\u1EA5p \u0111\u1ED9 9',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_9.json',
    length: 165,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel10',
    name: 'EF-LEVEL-10',
    description: 'EF C\u1EA5p \u0111\u1ED9 10',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_10.json',
    length: 174,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel11',
    name: 'EF-LEVEL-11',
    description: 'EF C\u1EA5p \u0111\u1ED9 11',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_11.json',
    length: 176,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel12',
    name: 'EF-LEVEL-12',
    description: 'EF C\u1EA5p \u0111\u1ED9 12',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_12.json',
    length: 170,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel13',
    name: 'EF-LEVEL-13',
    description: 'EF C\u1EA5p \u0111\u1ED9 13',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_13.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel14',
    name: 'EF-LEVEL-14',
    description: 'EF C\u1EA5p \u0111\u1ED9 14',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_14.json',
    length: 171,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel15',
    name: 'EF-LEVEL-15',
    description: 'EF C\u1EA5p \u0111\u1ED9 15',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_15.json',
    length: 168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel16',
    name: 'EF-LEVEL-16',
    description: 'EF C\u1EA5p \u0111\u1ED9 16',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_16.json',
    length: 170,
    language: 'en',
    languageCategory: 'en',
  },
  //Reading_Explorerloạt
  {
    id: 'ReadingExplorer3',
    name: 'Reading Explorer 3',
    description: 'T\u1EEB v\u1EF1ng t\u1EEB Reading Explorer 3 (Third Edition)',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['Kh\xE1c'],
    url: '/dicts/ReadingExplorer3.json',
    length: 239,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Macmillan7000',
    name: 'Macmillan 7000',
    description: 'Macmillan 7000',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Kh\xE1c'],
    url: '/dicts/Macmillan7000.json',
    length: 6268,
    language: 'en',
    languageCategory: 'en',
  },
  // RAZ loạt
  {
    id: 'raz-AA',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 AA',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 AA',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-AA.json',
    length: 422,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-A',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 A',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 A',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-A.json',
    length: 487,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-B',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 B',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 B',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-B.json',
    length: 465,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-C',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 C',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 C',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-C.json',
    length: 480,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-D',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 D',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 D',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-D.json',
    length: 436,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-E',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 E',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 E',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-E.json',
    length: 427,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-F',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 F',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 F',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-F.json',
    length: 437,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-G',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 G',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 G',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-G.json',
    length: 435,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-H',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 H',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 H',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-H.json',
    length: 385,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-I',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 I',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 I',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-I.json',
    length: 408,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-J',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 J',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 J',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-J.json',
    length: 434,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-K',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 K',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 K',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-K.json',
    length: 397,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-L',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 L',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 L',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-L.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-M',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 M',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 M',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-M.json',
    length: 403,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-N',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 N',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 N',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-N.json',
    length: 376,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-O',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 O',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 O',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-O.json',
    length: 429,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-P',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 P',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 P',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-P.json',
    length: 379,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Q',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Q',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Q',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Q.json',
    length: 442,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-R',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 R',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 R',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-R.json',
    length: 422,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-S',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 S',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 S',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-S.json',
    length: 434,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-T',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 T',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 T',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-T.json',
    length: 427,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-U',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 U',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 U',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-U.json',
    length: 418,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-V',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 V',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 V',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-V.json',
    length: 409,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-W',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 W',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 W',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-W.json',
    length: 392,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-X',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 X',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 X',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-X.json',
    length: 546,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Y',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Y',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Y',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Y.json',
    length: 461,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Z',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Z',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z.json',
    length: 414,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z1',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Z1',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Z1',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z1.json',
    length: 467,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z2',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Z2',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Z2',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z2.json',
    length: 492,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-all',
    name: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Tr\u1ECDn b\u1ED9',
    description: 'Reading A-Z (RAZ) C\u1EA5p \u0111\u1ED9 Tr\u1ECDn b\u1ED9',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-all.json',
    length: 5831,
    language: 'en',
    languageCategory: 'en',
  },
]
const japaneseExam = [
  {
    id: 'japanese-hiragana',
    name: 'Hiragana',
    description: 'Luy\u1EC7n t\u1EADp ch\u1EEF Hiragana',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n', 'Gojuon', 'Hiragana'],
    url: '/dicts/JapaneseHiragana.json',
    length: 280,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese-katakana',
    name: 'Katakana',
    description: 'Luy\u1EC7n t\u1EADp ch\u1EEF Katakana',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n', 'Gojuon', 'Katakana'],
    url: '/dicts/JapaneseKatakana.json',
    length: 280,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese001',
    name: 'Ti\u1EBFng Nh\u1EADt th\xF4ng d\u1EE5ng',
    description: 'D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Japanesebasicword.json',
    length: 100,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese001-zh',
    name: 'Ti\u1EBFng Nh\u1EADt th\xF4ng d\u1EE5ng',
    description: 'D\u1ECBch Nh\u1EADt - Trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Japanesebasicword_zh.json',
    length: 100,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese002',
    name: 'N5',
    description: 'D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N5.json',
    length: 670,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese002-zh',
    name: 'N5',
    description: 'D\u1ECBch Nh\u1EADt - Trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N5_zh.json',
    length: 670,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese003',
    name: 'N4',
    description: 'D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N4.json',
    length: 635,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese003-zh',
    name: 'N4',
    description: 'D\u1ECBch Nh\u1EADt - Trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N4_zh.json',
    length: 635,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese004',
    name: 'N3',
    description: 'D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N3.json',
    length: 1830,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese004-zh',
    name: 'N3',
    description: 'D\u1ECBch Nh\u1EADt - Trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N3_zh.json',
    length: 1830,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese005',
    name: 'N2',
    description: 'D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N2.json',
    length: 1836,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese005-zh',
    name: 'N2',
    description: 'D\u1ECBch Nh\u1EADt - Trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N2_zh.json',
    length: 1836,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese006',
    name: 'N1',
    description: 'D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N1.json',
    length: 3477,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese006-zh',
    name: 'N1',
    description: 'D\u1ECBch Nh\u1EADt - Trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N1_zh.json',
    length: 3477,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese007',
    name: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao N1',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao Ti\u1EBFng Nh\u1EADtN1',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N1.json',
    length: 3e3,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese008',
    name: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao N2',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao Ti\u1EBFng Nh\u1EADtN2',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N2.json',
    length: 2500,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese009',
    name: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao N3',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao Ti\u1EBFng Nh\u1EADtN3',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N3.json',
    length: 1999,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese0010',
    name: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao N4N5',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao Ti\u1EBFng Nh\u1EADtN4N5',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N4N5.json',
    length: 2e3,
    language: 'romaji',
    languageCategory: 'ja',
  },
]
const germanExam = [
  {
    id: 'german2en',
    name: '\u0110\u1EE9c - Anh',
    description: 'Ti\u1EBFng \u0110\u1EE9ct\u1EEB v\u1EF1ng, D\u1ECBch Nh\u1EADt - Anh',
    category: 'Ti\u1EBFng \u0110\u1EE9c',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/german2en.json',
    length: 5892,
    language: 'de',
    languageCategory: 'de',
  },
  {
    id: 'en2german',
    name: 'Anh - \u0110\u1EE9c',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh, D\u1ECBch Ti\u1EBFng \u0110\u1EE9c',
    category: 'Ti\u1EBFng \u0110\u1EE9c',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/en2german.json',
    length: 5025,
    language: 'en',
    languageCategory: 'de',
  },
]
const dictionaryResources = [
  ...generalEnglish,
  ...internationalExam,
  ...childrenEnglish,
  ...japaneseExam,
  ...germanExam,
  // {
  //   id: 'zhtest',
  //   name: 'thi tiếng trung',
  //   description: 'thi tiếng trungtừ vựng',
  //   category: 'Bài kiểm tra',
  //   url: '/dicts/chinese_test.json',
  //   length: 27,
  //   language: 'zh',
  // },
  // {
  //   id: 'jptest',
  //   name: 'ngàybài kiểm tra tiểu luận',
  //   description: 'ngàybài kiểm tra tiểu luậntừ vựng',
  //   category: 'Bài kiểm tra',
  //   url: '/dicts/japanese_test.json',
  //   length: 20,
  //   language: 'ja',
  // },
]
const dictionaries = dictionaryResources.map((resource) => ({
  ...resource,
  chapterCount: (0, import_utils.calcChapterCount)(resource.length),
}))
const idDictionaryMap = Object.fromEntries(dictionaries.map((dict) => [dict.id, dict]))
