'use strict'
var __defProp = Object.defineProperty
var __getOwnPropDesc = Object.getOwnPropertyDescriptor
var __getOwnPropNames = Object.getOwnPropertyNames
var __hasOwnProp = Object.prototype.hasOwnProperty
var __export = (target, all) => {
  for (var name in all) __defProp(target, name, { get: all[name], enumerable: true })
}
var __copyProps = (to, from, except, desc) => {
  if ((from && typeof from === 'object') || typeof from === 'function') {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable })
  }
  return to
}
var __toCommonJS = (mod) => __copyProps(__defProp({}, '__esModule', { value: true }), mod)
var dictionary_exports = {}
__export(dictionary_exports, {
  dictionaries: () => dictionaries,
  dictionaryResources: () => dictionaryResources,
  idDictionaryMap: () => idDictionaryMap,
})
module.exports = __toCommonJS(dictionary_exports)
var import_utils = require('@/utils')
const chinaExam = [
  {
    id: 'cet4',
    name: 'CET-4',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc (CET-4)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/CET4_T.json',
    length: 2607,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet6',
    name: 'CET-6',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc (CET-6)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/CET6_T.json',
    length: 2345,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'xinghuoqiaoji_4',
    name: 'CET-4 C\u1EA5p t\u1ED1c',
    description: 'CET-4 C\u1EA5p t\u1ED1c',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/xinghuoqiaoji_4.json',
    length: 2522,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'xinghuoqiaoji_6',
    name: 'CET-6 C\u1EA5p t\u1ED1c',
    description: 'CET-6 C\u1EA5p t\u1ED1c',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/xinghuoqiaoji_6.json',
    length: 7520,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet4-sub',
    name: 'CET-4 C\u01A1 b\u1EA3n',
    description: 'CET-4 R\xFAt g\u1ECDn',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/DanCiDeJianFa_4.json',
    length: 1957,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet6-sub',
    name: 'CET-6 C\u01A1 b\u1EA3n',
    description: 'CET-6 R\xFAt g\u1ECDn',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/DanCiDeJianFa_6.json',
    length: 1949,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyan',
    name: 'Thi Cao h\u1ECDc',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Thi Cao h\u1ECDc',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/KaoYan_3_T.json',
    length: 3728,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyan_2024',
    name: 'Thi Cao h\u1ECDc 2024',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Thi Cao h\u1ECDc 2024',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/KaoYan_2024.json',
    length: 3731,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyanshanguo_2023',
    name: 'Thi Cao h\u1ECDc 2023',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t Cao/Trung/Th\u1EA5p 2023',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/KaoYanShanGuo_2023.json',
    length: 1771,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '926',
    name: 'Thi Cao h\u1ECDc 926 t\u1EEB v\u1EF1ng',
    description: '926 t\u1EEB v\u1EF1ng c\u1ED1t l\xF5i',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/926.json',
    length: 926,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'dancimimi_1',
    name: 'Ti\u1EBFng Anh b\xED m\u1EADt 1',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh b\xED m\u1EADt (1)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/DanCiDeMimi_1.json',
    length: 5657,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'dancimimi_2',
    name: 'Ti\u1EBFng Anh b\xED m\u1EADt 2',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh b\xED m\u1EADt (2)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/DanCiDeMimi_2.json',
    length: 3827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2024HongBao T1',
    name: 'S\xE1ch \u0110\u1ECF Ti\u1EBFng Anh Cao H\u1ECDc 2024 (Ph\u1EA7n 1)',
    description: 'T\u1EEB v\u1EF1ng b\u1EAFt bu\u1ED9c S\xE1ch \u0110\u1ECF Cao H\u1ECDc 2024 (Ph\u1EA7n 1)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/2024HongBao_T1.json',
    length: 997,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2024HongBao T2',
    name: 'S\xE1ch \u0110\u1ECF Ti\u1EBFng Anh Cao H\u1ECDc 2024 (Ph\u1EA7n 2)',
    description: 'T\u1EEB v\u1EF1ng b\u1EAFt bu\u1ED9c S\xE1ch \u0110\u1ECF Cao H\u1ECDc 2024 (Ph\u1EA7n 2)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/2024HongBao_T2.json',
    length: 854,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'S\xE1ch \u0110\u1ECF-2026',
    name: 'S\xE1ch \u0110\u1ECF Ti\u1EBFng Anh Cao H\u1ECDc 2026',
    description:
      '2026 Thi Cao h\u1ECDct\u1EEB v\u1EF1ng (T\u1EEB v\u1EF1ng b\u1EAFt bu\u1ED9c+C\u0103n c\u1EE9t\u1EEB+N\xE2ng caot\u1EEB\uFF09',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/S\xE1ch \u0110\u1ECF-2026.json',
    length: 4858,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'English_II',
    name: 'Ti\u1EBFng Anhhait\u1EEB v\u1EF1ng',
    description: 'Thi Cao h\u1ECDc Ti\u1EBFng Anhhait\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/English_II.json',
    length: 4559,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyanshanguo2025',
    name: 'Thi Cao h\u1ECDc Shanguo 2025',
    description: 'Thi Cao h\u1ECDc Shanguo 2025',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/kaoyanshanguo2025.json',
    length: 2257,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'level4',
    name: 'Ti\u1EBFng Anh Chuy\xEAn ng\xE0nh 4 (TEM-4)',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Chuy\xEAn ng\xE0nh 4',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/Level4luan_2_T.json',
    length: 4025,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'level8',
    name: 'Ti\u1EBFng Anh Chuy\xEAn ng\xE0nh 8 (TEM-8)',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Chuy\xEAn ng\xE0nh 8',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/Level8luan_2_T.json',
    length: 12197,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'archVocabulary',
    name: 'Ti\u1EBFng Anh Ki\u1EBFn tr\xFAc',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh chuy\xEAn ng\xE0nh Ki\u1EBFn tr\xFAc',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Chuy\xEAn ng\xE0nh'],
    url: '/dicts/archVocabulary.json',
    length: 630,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'itVocabulary',
    name: 'Ti\u1EBFng Anh CNTT',
    description: '\u0110\u1EA1i h\u1ECDc huy\xEAn ng\xE0nh CNTTTi\u1EBFng Anht\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Chuy\xEAn ng\xE0nh'],
    url: '/dicts/itVocabulary.json',
    length: 1665,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'pets3',
    name: 'PETS',
    description: 'T\u1EEB v\u1EF1ng k\xEC thi Ti\u1EBFng Anh to\xE0n qu\u1ED1c',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['PET'],
    url: '/dicts/PETS_3.json',
    length: 1942,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'pets3-2023',
    name: 'PETS 2023',
    description: 'T\u1EEB v\u1EF1ng k\xEC thi Ti\u1EBFng Anh to\xE0n qu\u1ED1c',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['PET'],
    url: '/dicts/PETS3-2023.json',
    length: 4449,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English1',
    name: '1800 t\u1EEB v\u1EF1ng t\u1EF1 h\u1ECDc t\u1EA7n su\u1EA5t cao',
    description: '1800 t\u1EEB v\u1EF1ng t\u1EF1 h\u1ECDc t\u1EA7n su\u1EA5t cao',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['T\u1EF1 h\u1ECDc Ti\u1EBFng Anh'],
    url: '/dicts/self-study_English1.json',
    length: 1800,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English2',
    name: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh t\u1EF1 h\u1ECDc t\u1EA7n su\u1EA5t cao',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh t\u1EF1 h\u1ECDc t\u1EA7n su\u1EA5t cao',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['T\u1EF1 h\u1ECDc Ti\u1EBFng Anh'],
    url: '/dicts/self-study_English2.json',
    length: 2181,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English3',
    name: 't\u1EF1 h\u1ECDcTi\u1EBFng Anhhaitr\u1ECDnt\u1EEB',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh T\u1EF1 h\u1ECDc 2 (Tr\u1ECDn b\u1ED9)',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['T\u1EF1 h\u1ECDc Ti\u1EBFng Anh'],
    url: '/dicts/self-study_English3.json',
    length: 4603,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'coca_20000',
    name: 'COCA20000t\u1EEB',
    description: 'COCA20000t\u1EEB',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/coca20000.json',
    length: 20199,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words1',
    name: 'Essential Words',
    description: '4000 Essential English Words meaning',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/4000_Essential_English_Words-meaning.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words2',
    name: 'Essential Words',
    description: '4000 Essential English Words sentence',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/4000_Essential_English_Words-sentence.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'longman_communication_3000_words',
    name: 'Longman Communication 3000',
    description: 'Most frequent words in both spoken and written English',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Longman_Communication_3000.json',
    length: 3168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_2000_English_Words',
    name: 'Top 2000 words',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/top2000words.json',
    length: 1867,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1500_nouns_Words',
    name: 'Top 1500 Nouns',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top1500NounWords.json',
    length: 1525,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1000_verb_Words',
    name: 'Top 1000 Verbs',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top1000VerbWords.json',
    length: 1011,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_500_Adj_Words',
    name: 'Top 500 adj.',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top500AdjectiveWords.json',
    length: 527,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_250_Adv_Words',
    name: 'Top 250 adv.',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top250AdverbWords.json',
    length: 255,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_60_Pronouns',
    name: 'Top 60 pron.',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top60Pronouns.json',
    length: 59,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_50_Prepositions',
    name: 'Top 50 prep.',
    description: 'with highest frequency',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Top50Prepositions.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'suffix word',
    name: 'suffix word',
    description: 'common suffix',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/suffix_word.json',
    length: 126,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'word roots1',
    name: 'word roots1',
    description: 'common roots',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/word_roots1.json',
    length: 369,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'adult self-study examination',
    name: 'Li\xEAn th\xF4ng \u0110\u1EA1i h\u1ECDct\u1EEB v\u1EF1ng',
    description: 'Li\xEAn th\xF4ng \u0110\u1EA1i h\u1ECDct\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/adult-self-study-examination.json',
    length: 3692,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhuan-cha-ben-ying-yu',
    name: 'Chuy\xEAn tu \u0110\u1EA1i h\u1ECDcTi\u1EBFng Anht\u1EEB v\u1EF1ng',
    description: 'Chuy\xEAn tu \u0110\u1EA1i h\u1ECDcTi\u1EBFng Anht\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/zhuan-cha-ben.json',
    length: 3217,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhuan-sheng-ben-xue-shi',
    name: 'Ti\u1EBFng Anh C\u1EED nh\xE2n',
    description: 'Ti\u1EBFng Anh C\u1EED nh\xE2n',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/xueshiyingyu.json',
    length: 897,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford5000t\u1EEB',
    description: 'Oxford5000t\u1EEB',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Merriam_Webster_sVocabularyBuilder',
    name: 'c\u1EE7a WebsterT\u1EEB \u0111i\u1EC3n g\u1ED1c t\u1EEB',
    description: 'c\u1EE7a WebsterT\u1EEB \u0111i\u1EC3n g\u1ED1c t\u1EEB',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Merriam_Webster_sVocabularyBuilder.json',
    length: 1191,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'tingshuokaoshi',
    name: 'T\u1EEB v\u1EF1ng Nghe hi\u1EC3u Ph\u1ED5 bi\u1EBFnt\u1EEB v\u1EF1ng',
    description: '16 ch\u1EE7 \u0111\u1EC1 Nghe hi\u1EC3u ph\u1ED5 bi\u1EBFnt\u1EEBH\u1ED3i T\xEDch',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/tingshuokaoshi.json',
    length: 557,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEFL_ZhangHongYan',
    name: 'T\u1EEB v\u1EF1ng TOEFL (ZhangHongYan)',
    description: 'T\u1EEB v\u1EF1ng TOEFL (ZhangHongYan) - Theo ch\u1EE7 \u0111\u1EC1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_ZhangHongYan.json',
    length: 4032,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2025KaoYanHongBaoShu',
    name: '2025Thi Cao h\u1ECDc Ti\u1EBFng Anht\u1EEB v\u1EF1nghongbaoS\xE1ch',
    description: '2025Thi Cao h\u1ECDc Ti\u1EBFng Anht\u1EEB v\u1EF1nghongbaoS\xE1ch',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Thi Cao h\u1ECDc'],
    url: '/dicts/2025KaoYanHongBaoShu.json',
    length: 6705,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '3000_ClassRoom_English_Words',
    name: 'Li\xEAn th\xF4ng \u0110\u1EA1i h\u1ECDc3000t\u1EEB',
    description: 'Li\xEAn th\xF4ng \u0110\u1EA1i h\u1ECDct\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Ti\u1EBFng Anh \u0110\u1EA1i h\u1ECDc'],
    url: '/dicts/3000_ClassRoom_English_Words.json',
    length: 2991,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'frequently_used_words01',
    name: 'T\u1EEB v\u1EF1ng c\u1EA5p t\u1ED1c level 1',
    description: 'T\u1EEB v\u1EF1ng c\u1EA5p t\u1ED1c level 1',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/frequently_used_word01.json',
    length: 679,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'frequently_used_words03',
    name: 'T\u1EEB v\u1EF1ng c\u1EA5p t\u1ED1c level 2',
    description: 'T\u1EEB v\u1EF1ng c\u1EA5p t\u1ED1c level 2',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/frequently_used_word02.json',
    length: 1040,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'frequently_used_words03',
    name: 'T\u1EEB v\u1EF1ng c\u1EA5p t\u1ED1c level 3',
    description: 'T\u1EEB v\u1EF1ng c\u1EA5p t\u1ED1c level 3',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/frequently_used_word03.json',
    length: 1435,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'roger',
    name: "Roger's Words",
    description: 'D\xF9ng trong h\u1ECDc t\u1EADp & c\xF4ng vi\u1EC7cTi\u1EBFng Anh',
    category: 'T\u1EEB \u0111i\u1EC3n Ti\u1EBFng Anh',
    tags: ['Ngo\u1EA1i kho\xE1'],
    url: '/dicts/RogersWords.json',
    length: 4174,
    language: 'en',
    languageCategory: 'en',
  },
]
const internationalExam = [
  {
    id: 'pet-2024',
    name: 'PET-2024',
    description: 'CambridgeTi\u1EBFng Anh - 2024',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PET'],
    url: '/dicts/pet-vacabulary-list-2024.json',
    length: 1871,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gmat',
    name: 'GMAT',
    description: 'GMAT t\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GMAT'],
    url: '/dicts/GMAT_3_T.json',
    length: 3047,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre',
    name: 'GRE',
    description: 'GRE t\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE_3_T.json',
    length: 6515,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre1500',
    name: 'GREt\u1EADp trung1500t\u1EEB-fenanh trai',
    description: 'T\u1EEB v\u1EF1ng T\u1EA7n su\u1EA5t cao GRE & TEM8',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE_1500.json',
    length: 1533,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre3000',
    name: 'GRE3000',
    description: 'T\u1EEB v\u1EF1ng GRE3000',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE3000_3_T.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE-computer-based-test',
    name: 'GRET\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    description: 'GRET\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE-computer-based-test.json',
    length: 1451,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ZaiYaoNiMing_GRE3000',
    name: 'GRE3000 T\xE1i xu\u1EA5t',
    description: 'GRE3000 T\xE1i xu\u1EA5tt\u1EEB v\u1EF1ng-c\xF3t\u1EEBphi\xEAn b\u1EA3n m\u1EDBi c\u1EE7a t\xECnh d\u1EE5c',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/ZaiYaoNiMing_GRE3000.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_equivalent',
    name: 'T\u1EEB \u0111\u1ED3ng ngh\u0129a GRE',
    description: 'T\u1EEB \u0111\u1ED3ng ngh\u0129a GRE',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/GRE_equivalent.json',
    length: 827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_ciyileiji',
    name: 'GREt\u1EEBTheo ch\u1EE7 \u0111\u1EC1',
    description: 'GREt\u1EEBTheo ch\u1EE7 \u0111\u1EC1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['GRE'],
    url: '/dicts/gre-ciyileiji.json',
    length: 8785,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'biomedical-terms',
    name: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Y sinh',
    description: 'T\u1EEB v\u1EF1ng Ti\u1EBFng Anh Y sinh',
    category: 'T\u1EEB v\u1EF1ng chuy\xEAn ng\xE0nh',
    tags: ['Sinh h\u1ECDc'],
    url: '/dicts/BIOmedical.json',
    length: 560,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS_tinglichangjing',
    name: 'Ch\u1EE7 \u0111\u1EC1 Nghe IELTSt\u1EEB v\u1EF1ng',
    description: 'Ch\u1EE7 \u0111\u1EC1 Nghe IELTSt\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_tinglichangjing.json',
    length: 1204,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_disorder',
    name: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Ng\u1EABu nhi\xEAn)',
    description: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Ng\u1EABu nhi\xEAn)',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_disorder.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_order',
    name: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Theo th\u1EE9 t\u1EF1)',
    description: 'IELTSB\u1EA3n \u0111\u1EA7y \u0111\u1EE7 (Theo th\u1EE9 t\u1EF1)',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_order.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts',
    name: 'IELTS',
    description: 'IELTSt\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_3_T.json',
    length: 3575,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'heqiong',
    name: 'T\u1EEB v\u1EF1ng IELTS Listening (heQiong)t\u1EEB v\u1EF1ng',
    description: '\u0110\u1EC1 t\u1ED5ng h\u1EE3p',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/HeQiong_IELTS.json',
    length: 2529,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang3',
    name: 'IELTS Wang C3',
    description: 'Danh t\u1EEB ri\xEAng IELTS Listeningt\u1EEB\u0111\u1EC1 thi',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_3.json',
    length: 1135,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang4',
    name: 'IELTS Wang C4',
    description: 'T\xEDnh t\u1EEB/Ph\xF3 t\u1EEB IELTS Listeningt\u1EEBph\xF3t\u1EEB\u0111\u1EC1 thi',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_4.json',
    length: 346,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang5',
    name: 'IELTS Wang C5',
    description: 'Luy\u1EC7n t\u1EADp n\u1ED1i \xE2m v\xE0 nu\u1ED1t \xE2m',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_5.json',
    length: 1569,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang11',
    name: 'IELTS Wang C11',
    description: '\u0110\u1EC1 t\u1ED5ng h\u1EE3p',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_11.json',
    length: 1738,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'DuckCircle_IELTS',
    name: 'T\u1EEB v\u1EF1ng IELTS c\u1ED1t l\xF5i (Yaquan)t\u1EEB',
    description: 'T\u1EEB v\u1EF1ng IELTS c\u1ED1t l\xF5i (Yaquan)t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/DuckCircle_IELTS.json',
    length: 2644,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSVocabularyBible',
    name: 'IELTSt\u1EEBHuizhen Jing',
    description: 'IELTSt\u1EEBHuizhen Jing',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTSVocabularyBible.json',
    length: 3673,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-807',
    name: 'IELTS wanglu 807',
    description: 'IELTS wanglu 807',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-807.json',
    length: 4340,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-high',
    name: 'IELTS real t\u1EEB v\u1EF1ng t\u1EA7n su\u1EA5t cao',
    description: 'IELTS real t\u1EEB v\u1EF1ng\uFF08t\u1EA7n su\u1EA5t caot\u1EEB v\u1EF1ng\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-high.json',
    length: 524,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-5',
    name: 'IELTS real t\u1EEB v\u1EF1ng 5',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF085T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-5.json',
    length: 183,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-4',
    name: 'IELTS real t\u1EEB v\u1EF1ng 4',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF084T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-4.json',
    length: 201,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-3',
    name: 'IELTS real t\u1EEB v\u1EF1ng 3',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF083T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-3.json',
    length: 256,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-2',
    name: 'IELTS real t\u1EEB v\u1EF1ng 2',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF082T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-2.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-1',
    name: 'IELTS real t\u1EEB v\u1EF1ng 1',
    description:
      'IELTS real t\u1EEB v\u1EF1ng \uFF081T\xEDnh th\u01B0\u1EDDng xuy\xEAnt\u1EEBHui v\xE0 chuy\u1EC3n \u0111\u1ED5i t\u1EA7n su\u1EA5t\uFF09',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-1.json',
    length: 737,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS9988wangyong',
    name: 'IELTS9988wangyong',
    description: 'IELTS9988wangyong',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS9988wangyong.json',
    length: 3698,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSKingLu807',
    name: 'wanglu807IELTSt\u1EEBHu\u1EC7 Th\xEDnhKH\xD4NG.2phi\xEAn b\u1EA3n',
    description: 'wanglu807IELTSt\u1EEBHu\u1EC7 Th\xEDnhKH\xD4NG.2phi\xEAn b\u1EA3n',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTSKingLu807.json',
    length: 1916,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSXDF7000',
    name: '100N\xF3i xong c\xE2u7000IELTSt\u1EEB',
    description: 'xdf 100N\xF3i xong c\xE2u7000IELTSt\u1EEB t\u1EEBTuy\xEAn b\u1ED1 trao \u0111\u1ED5i',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS_XDF_7000.json',
    length: 5567,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-oral-900',
    name: 'N\xF3i IELTS 900 betaphi\xEAn b\u1EA3n',
    description:
      'N\xF3i IELTS 900 c\xE2u, nhu c\u1EA7uhi\u1EC7n h\u1EEFu qwerty c\xE0i \u0111\u1EB7t\xC2m trung nh\u1ECFTi\u1EBFng Anhph\xF4ng ch\u1EEF',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-oral-900.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task1',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day1',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task1.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task2',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day2',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day2',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task2.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task3',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day3',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day3',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task3.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task4',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day4',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day4',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task4.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task5',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day5',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day5',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task5.json',
    length: 38,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task6',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day6',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day6',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task6.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task7',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day7',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day7',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task7.json',
    length: 39,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task8',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day8',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day8',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task8.json',
    length: 32,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task9',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day9',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day9',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task9.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task10',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day10',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day10',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task10.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task11',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day11',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day11',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task11.json',
    length: 36,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task12',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day12',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day12',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task12.json',
    length: 45,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task13',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day13',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day13',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task13.json',
    length: 49,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task14',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day14',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day14',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task14.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task15',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day15',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day15',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task15.json',
    length: 29,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task16',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day16',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day16',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task16.json',
    length: 42,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task17',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day17',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day17',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task17.json',
    length: 22,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task18',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day18',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day18',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task18.json',
    length: 37,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task19',
    name: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day19',
    description: 'xdfth\xEDnh gi\xE1c IELTS trung c\u1EA5p c\u1EA5p t\u1ED1c day19',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task19.json',
    length: 26,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-1',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day1',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day1.json',
    length: 74,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-2',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day2',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day2',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day2.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-3',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day3',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day3',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day3.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-4',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day4',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day4',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day4.json',
    length: 73,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-5',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day5',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day5',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day5.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-6',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day6',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day6',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day6.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-7',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day7',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day7',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day7.json',
    length: 75,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-8',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day8',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day8',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day8.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-9',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day9',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day9',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day9.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-10',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day10',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day10',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day10.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-11',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day11',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day11',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day11.json',
    length: 52,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-12',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day12',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day12',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day12.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-13',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day13',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day13',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day13.json',
    length: 78,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-14',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day14',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day14',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day14.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-15',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day15',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day15',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day15.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-16',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day16',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day16',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day16.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-17',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day17',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day17',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day17.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-18',
    name: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day18',
    description: 'Luy\u1EC7n nghe IELTSt\u1EEB v\u1EF1ng18b\u1EA7u tr\u1EDDi day18',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day18.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ket',
    name: 'KET',
    description: 'KET 2021t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['KET'],
    url: './dicts/ket2021.json',
    length: 1147,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'sat',
    name: 'SAT',
    description: 'Hoa K\u1EF3 SAT T\u1EEB v\u1EF1ng thi',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['SAT'],
    url: '/dicts/SAT_3_T.json',
    length: 4464,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SATen',
    name: 'SAT en-en',
    description: 'SATYingying',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['SAT'],
    url: '/dicts/SATen.json',
    length: 2681,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'toefl',
    name: 'TOEFL',
    description: '\u0110\u1EC1 thi TOEFL ph\u1ED5 bi\u1EBFnt\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_3_T.json',
    length: 4264,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'bec2',
    name: 'Ti\u1EBFng Anh th\u01B0\u01A1ng m\u1EA1i',
    description: 'Ti\u1EBFng Anh th\u01B0\u01A1ng m\u1EA1ichungt\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['BEC'],
    url: '/dicts/BEC_2_T.json',
    length: 2753,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'bec3',
    name: 'BEC',
    description: 'BECC\xE1c k\u1EF3 thi chungt\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['BEC'],
    url: '/dicts/BEC_3_T.json',
    length: 2825,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_junior',
    name: 'PTE C\u0103n c\u1EE9t\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_junior.json',
    length: 2651,
    language: 'en',
    languageCategory: 'en',
  },
  // {
  //   id: 'PTE_WFDgaopinci.json',
  //   name: 'PTE WFDtần suất caotừ vựng',
  //   description: 'WFDtần suất caotừchìm từ cao xuống thấp，sự thành thạo tối thiểu350cá nhân',
  //   category: 'Kỳ thi Quốc tế',
  //   tags: ['PTE'],
  //   url: '/dicts/PTE_WFDgaopinci.json',
  //   length: 1175,
  //   language: 'en',
  //   languageCategory: 'en',
  // },
  {
    id: 'PTE_senior',
    name: 'PTE Tr\xECnh \u0111\u1ED9 caot\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_senior.json',
    length: 3170,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_R_junior',
    name: '\u0111\u1ECDc FIB C\u01A1 h\u1ECDc c\u01A1 b\u1EA3nt\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_R_junior.json',
    length: 941,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_R_senior',
    name: '\u0111\u1ECDc FIB M\xE1y m\xF3c ti\xEAn ti\u1EBFnt\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_R_senior.json',
    length: 1272,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_WFD',
    name: 'WFD T\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_WFD.json',
    length: 1212,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_L',
    name: 'th\xEDnh gi\xE1c FIB T\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_L.json',
    length: 646,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Basic_apeuni',
    name: 'PTE C\u0103n c\u1EE9t\u1EEB v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Basic_apeuni.json',
    length: 2652,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Advanced_apeuni.json',
    name: 'PTE Tr\xECnh \u0111\u1ED9 caot\u1EEB v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Advanced_apeuni.json',
    length: 3169,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Read_apeuni.json',
    name: 'PTE \u0111\u1ECDcFIBT\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Read_apeuni.json',
    length: 630,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Listening_apeuni.json',
    name: 'PTE th\xEDnh gi\xE1cFIBT\u1EEB v\u1EF1ng tr\xEAn m\xE1y t\xEDnh v\u1EF1ng xingji',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/PTE_Listening_apeuni.json',
    length: 674,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEIC',
    name: 'TOEIC t\u1EEB v\u1EF1ng',
    description: '',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEIC'],
    url: '/dicts/TOEIC.json',
    length: 1694,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_B1',
    name: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB1',
    description: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_B1.json',
    length: 801,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_B2',
    name: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB2',
    description: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngB2',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_B2.json',
    length: 1423,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_C1',
    name: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngC1',
    description: 'nhi\u1EC1uph\xE2n lo\u1EA1i h\xE0ng x\xF3mt\u1EEB v\u1EF1ngC1',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_C1.json',
    length: 1314,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford3000',
    name: 'Oxford3000t\u1EEB',
    description: 'Oxford3000t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['Phi\xEAn b\u1EA3n Oxford'],
    url: '/dicts/Oxford3000.json',
    length: 1342,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford5000t\u1EEB',
    description: 'Oxford5000t\u1EEB',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['Phi\xEAn b\u1EA3n Oxford'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'voa',
    name: 'VOA C\u0103n c\u1EE9t\u1EEB v\u1EF1ng',
    description: 'VOA C\u0103n c\u1EE9t\u1EEB v\u1EF1ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['Kh\xE1c'],
    url: '/dicts/voa.json',
    length: 1505,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Common-Phrases-PTE-Unofficial',
    name: 'PTE C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng (kh\xF4ng ch\xEDnh th\u1EE9c)',
    description: 'PTE C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['PTE'],
    url: '/dicts/Common-Phrases-PTE-Unofficial.json',
    length: 274,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Common-Phrases-FCE-Unofficial',
    name: 'FCE C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng (kh\xF4ng ch\xEDnh th\u1EE9c)',
    description: 'FCE C\u1EE5m t\u1EEB th\xF4ng d\u1EE5ng',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['FCE'],
    url: '/dicts/Common-Phrases-FCE-Unofficial.json',
    length: 438,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Categorized_TOEFL_Vocabulary_by_Zhanghongyan',
    name: 'Categorized Vocab.',
    description:
      't\u1EEBTheo ch\u1EE7 \u0111\u1EC1 TOEFL 2021 by ZhangHongYan (s\xE1ch g\u1ED1c Ngh\u0129a v\xE0 ghi nh\u1EDB; t\u1EEBs\u1EF1 li\xEAn ti\u1EBFpCon s\u1ED1)',
    category: 'K\u1EF3 thi Qu\u1ED1c t\u1EBF',
    tags: ['TOEFL'],
    url: '/dicts/Categorized_TOEFL_Vocabulary_by_Zhanghongyan.json',
    length: 4123,
    language: 'en',
    languageCategory: 'en',
  },
]
const childrenEnglish = [
  {
    id: 'gaokao3500',
    name: 'k\u1EF3 thi tuy\u1EC3n sinh \u0111\u1EA1i h\u1ECDc 3500 t\u1EEB',
    description: 'K\u1EF3 thi tuy\u1EC3n sinh \u0111\u1EA1i h\u1ECDc ph\u1ED5 th\xF4ngt\u1EEB 3500',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/GaoKao_3500.json',
    length: 3893,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gaokaozhentihexin',
    name: 'K\u1EF3 thi tuy\u1EC3n sinh \u0111\u1EA1i h\u1ECDc C\xE2u h\u1ECFi thi tr\u01B0\u1EDBc \u0111\xE2y T\u1EA7n su\u1EA5t cao',
    description:
      'K\u1EF3 thi tuy\u1EC3n sinh \u0111\u1EA1i h\u1ECDc C\xE2u h\u1ECFi thi tr\u01B0\u1EDBc \u0111\xE2y T\u1EA7n su\u1EA5t cao',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/GaoKaoZhenTiHeXinGaoPin.json',
    length: 799,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gaokao-yuedu-gaopin',
    name: 'k\u1EF3 thi tuy\u1EC3n sinh \u0111\u1EA1i h\u1ECDcTi\u1EBFng Anh\u0110\u1ECDc t\u1EA7n su\u1EA5t caot\u1EEB v\u1EF1ng',
    description: 'k\u1EF3 thi tuy\u1EC3n sinh \u0111\u1EA1i h\u1ECDcTi\u1EBFng Anh\u0110\u1ECDc t\u1EA7n su\u1EA5t caot\u1EEB v\u1EF1ng',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/gaokao-yuedu-gaopin.json',
    length: 688,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhongkaohexin',
    name: 'C\u1ED1t l\xF5i k\u1EF3 thi tuy\u1EC3n sinh trung h\u1ECDct\u1EEB',
    description: 'C\u1ED1t l\xF5i k\u1EF3 thi tuy\u1EC3n sinh trung h\u1ECDct\u1EEB',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/ZhongKaoHeXin.json',
    length: 2140,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce1',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh-1',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng AnhKH\xD4NG.m\u1ED9ts\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_1.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce2',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh-2',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng AnhKH\xD4NG.hais\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_2.json',
    length: 858,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce3',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh-3',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng AnhKH\xD4NG.bas\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_3.json',
    length: 1052,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce4',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh-4',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng AnhKH\xD4NG.b\u1ED1ns\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_4.json',
    length: 784,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-1',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh(phi\xEAn b\u1EA3n m\u1EDBi)-1',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anhphi\xEAn b\u1EA3n m\u1EDBiKH\xD4NG.m\u1ED9ts\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-1.json',
    length: 908,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-2',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh(phi\xEAn b\u1EA3n m\u1EDBi)-2',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anhphi\xEAn b\u1EA3n m\u1EDBiKH\xD4NG.hais\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-2.json',
    length: 862,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-3',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh(phi\xEAn b\u1EA3n m\u1EDBi)-3',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anhphi\xEAn b\u1EA3n m\u1EDBiKH\xD4NG.bas\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-3.json',
    length: 1062,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-4',
    name: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anh(phi\xEAn b\u1EA3n m\u1EDBi)-4',
    description: 'kh\xE1i ni\u1EC7m m\u1EDBiTi\u1EBFng Anhphi\xEAn b\u1EA3n m\u1EDBiKH\xD4NG.b\u1ED1ns\xE1ch',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-4.json',
    length: 793,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SHjuniormiddleOxford',
    name: 'Tr\u01B0\u1EDDng trung h\u1ECDc c\u01A1 s\u1EDF Th\u01B0\u1EE3ng H\u1EA3i Oxfordt\u1EEB v\u1EF1ng',
    description: 'Tr\u01B0\u1EDDng trung h\u1ECDc c\u01A1 s\u1EDF Th\u01B0\u1EE3ng H\u1EA3i Oxfordt\u1EEB v\u1EF1ng',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['Phi\xEAn b\u1EA3n Oxford'],
    url: '/dicts/OxfordVocabulary_juniorMiddleSH.json',
    length: 1270,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'BJJuniorHigh',
    name: 'Tr\u01B0\u1EDDng trung h\u1ECDc c\u01A1 s\u1EDF B\u1EAFc Kinh',
    description: 'Tr\u01B0\u1EDDng trung h\u1ECDc c\u01A1 s\u1EDF B\u1EAFc Kinh',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['Kh\xE1c'],
    url: '/dicts/beijing_junior_high_school.json',
    length: 1844,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel1',
    name: 'EF-LEVEL-1',
    description: 'EFc\u1EA5p1',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_1.json',
    length: 297,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel2',
    name: 'EF-LEVEL-2',
    description: 'EFc\u1EA5p2',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_2.json',
    length: 353,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel3',
    name: 'EF-LEVEL-3',
    description: 'EFc\u1EA5p3',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_3.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel4',
    name: 'EF-LEVEL-4',
    description: 'EFc\u1EA5p4',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_4.json',
    length: 178,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel5',
    name: 'EF-LEVEL-5',
    description: 'EFc\u1EA5p5',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_5.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel6',
    name: 'EF-LEVEL-6',
    description: 'EFc\u1EA5p6',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_6.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel7',
    name: 'EF-LEVEL-7',
    description: 'EFc\u1EA5p7',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_7.json',
    length: 171,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel8',
    name: 'EF-LEVEL-8',
    description: 'EFc\u1EA5p8',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_8.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel9',
    name: 'EF-LEVEL-9',
    description: 'EFc\u1EA5p9',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_9.json',
    length: 165,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel10',
    name: 'EF-LEVEL-10',
    description: 'EFc\u1EA5p10',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_10.json',
    length: 174,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel11',
    name: 'EF-LEVEL-11',
    description: 'EFc\u1EA5p11',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_11.json',
    length: 176,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel12',
    name: 'EF-LEVEL-12',
    description: 'EFc\u1EA5p12',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_12.json',
    length: 170,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel13',
    name: 'EF-LEVEL-13',
    description: 'EFc\u1EA5p13',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_13.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel14',
    name: 'EF-LEVEL-14',
    description: 'EFc\u1EA5p14',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_14.json',
    length: 171,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel15',
    name: 'EF-LEVEL-15',
    description: 'EFc\u1EA5p15',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_15.json',
    length: 168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel16',
    name: 'EF-LEVEL-16',
    description: 'EFc\u1EA5p16',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_16.json',
    length: 170,
    language: 'en',
    languageCategory: 'en',
  },
  //Reading_Explorerloạt
  {
    id: 'ReadingExplorer3',
    name: 'Reading Explorer 3',
    description: 't\u1EEBB\u1EA3ng trao \u0111\u1ED5i xu\u1EA5t ph\xE1t t\u1EEBReading Explorer 3, Third Edition',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['Kh\xE1c'],
    url: '/dicts/ReadingExplorer3.json',
    length: 239,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Macmillan7000',
    name: 'macmillan7000',
    description: 'macmillan7000',
    category: 'K\u1EF3 thi Trung Qu\u1ED1c',
    tags: ['Kh\xE1c'],
    url: '/dicts/Macmillan7000.json',
    length: 6268,
    language: 'en',
    languageCategory: 'en',
  },
  // RAZ loạt
  {
    id: 'raz-AA',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i AA',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i AA',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-AA.json',
    length: 422,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-A',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i A',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i A',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-A.json',
    length: 487,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-B',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i B',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i B',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-B.json',
    length: 465,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-C',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i C',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i C',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-C.json',
    length: 480,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-D',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i D',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i D',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-D.json',
    length: 436,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-E',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i E',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i E',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-E.json',
    length: 427,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-F',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i F',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i F',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-F.json',
    length: 437,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-G',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i G',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i G',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-G.json',
    length: 435,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-H',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i H',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i H',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-H.json',
    length: 385,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-I',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i I',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i I',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-I.json',
    length: 408,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-J',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i J',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i J',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-J.json',
    length: 434,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-K',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i K',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i K',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-K.json',
    length: 397,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-L',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i L',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i L',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-L.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-M',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i M',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i M',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-M.json',
    length: 403,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-N',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i N',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i N',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-N.json',
    length: 376,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-O',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i O',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i O',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-O.json',
    length: 429,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-P',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i P',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i P',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-P.json',
    length: 379,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Q',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Q',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Q',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Q.json',
    length: 442,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-R',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i R',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i R',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-R.json',
    length: 422,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-S',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i S',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i S',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-S.json',
    length: 434,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-T',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i T',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i T',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-T.json',
    length: 427,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-U',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i U',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i U',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-U.json',
    length: 418,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-V',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i V',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i V',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-V.json',
    length: 409,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-W',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i W',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i W',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-W.json',
    length: 392,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-X',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i X',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i X',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-X.json',
    length: 546,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Y',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Y',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Y',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Y.json',
    length: 461,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Z',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Z',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z.json',
    length: 414,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z1',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Z1',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Z1',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z1.json',
    length: 467,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z2',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Z2',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i Z2',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z2.json',
    length: 492,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-all',
    name: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i t\u1EA5t c\u1EA3t\u1EEB v\u1EF1ng',
    description: 'RAZ \u0110\u1ECDc \u0111\u01B0\u1EE3c x\u1EBFp lo\u1EA1i t\u1EA5t c\u1EA3t\u1EEB v\u1EF1ng',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['RAZ'],
    url: '/dicts/raz-all.json',
    length: 5831,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Cambridge_JOIN_IN',
    name: 'Tr\u01B0\u1EDDng ti\u1EC3u h\u1ECDc CambridgeTi\u1EBFng Anh JOIN IN',
    description:
      'Nh\xE0 xu\u1EA5t b\u1EA3n nghi\xEAn c\u1EE9u ngo\u1EA1i ng\u1EEFV\xE0Nh\xE0 xu\u1EA5t b\u1EA3n \u0110\u1EA1i h\u1ECDc Cambridge\u300Agi\xE1o d\u1EE5c b\u1EAFt bu\u1ED9cTi\u1EBFng AnhTi\xEAu chu\u1EA9n ch\u01B0\u01A1ng tr\xECnh gi\u1EA3ng d\u1EA1y\u300Bnhu c\u1EA7u \u0111o\xE0n th\u1EC3v\xECT\xD4ITr\u01B0\u1EDDng ti\u1EC3u h\u1ECDch\u1ECDc sinhph\xE1t tri\u1EC3nc\u1EE7am\u1ED9tb\u1ED9Ti\u1EBFng AnhS\xE1ch gi\xE1o khoa\u3002',
    category: 'Ti\u1EBFng Anh Tr\u1EBB em',
    tags: ['Kh\xE1c'],
    url: '/dicts/Cambridge_JOIN_IN.json',
    length: 1350,
    language: 'en',
    languageCategory: 'en',
  },
]
const programming = [
  {
    id: 'coder',
    name: 'Coder Dict',
    description: 'l\u1EADp tr\xECnh vi\xEAnchungt\u1EEBt\u1EEB v\u1EF1ng',
    category: 'L\u1EADp tr\xECnh',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/it-words.json',
    length: 1700,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'childCode',
    name: 'm\u1ED9t v\xE0iCon trai Python',
    description: 'm\u1ED9t v\xE0iCon trai Python chungt\u1EEB',
    category: 'L\u1EADp tr\xECnh',
    tags: ['L\u1EADp tr\xECnh tr\u1EBB em', 'Python'],
    url: '/dicts/Child_python_code.json',
    length: 19,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'childCode002',
    name: 'm\u1ED9t v\xE0iCon trai Python Turtle',
    description: 'm\u1ED9t v\xE0iCon trai Python Turtle chungt\u1EEB',
    category: 'L\u1EADp tr\xECnh',
    tags: ['L\u1EADp tr\xECnh tr\u1EBB em', 'Python'],
    url: '/dicts/Child_python_turtle_code.json',
    length: 27,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'childCode003',
    name: 'm\u1ED9t v\xE0iCon trai C++',
    description: 'm\u1ED9t v\xE0iCon trai C++ chungt\u1EEB',
    category: 'L\u1EADp tr\xECnh',
    tags: ['L\u1EADp tr\xECnh tr\u1EBB em', 'C++'],
    url: '/dicts/Child_cpp.json',
    length: 39,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'oi-xcpc',
    name: 'OI / XCPC cu\u1ED9c thit\u1EEB v\u1EF1ng',
    description: 'OI / XCPC cu\u1ED9c thit\u1EEB v\u1EF1ng',
    category: 'L\u1EADp tr\xECnh',
    tags: ['C++'],
    url: '/dicts/OI_XCPC.json',
    length: 195,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'childCode004',
    name: 'Arduino',
    description: 'Arduinochungt\u1EEB',
    category: 'L\u1EADp tr\xECnh',
    tags: ['L\u1EADp tr\xECnh tr\u1EBB em', 'Arduino'],
    url: '/dicts/arduino_keywords.json',
    length: 78,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'jsArray',
    name: 'JS: Array',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-array.json',
    length: 36,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsDate',
    name: 'JS: Date',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-date.json',
    length: 34,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsGlobal',
    name: 'JS: Global',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-global.json',
    length: 9,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsMapSet',
    name: 'JS: Map & Set',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-map-set.json',
    length: 16,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsMath',
    name: 'JS: Math',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-math.json',
    length: 38,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsNumber',
    name: 'JS: Number',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-number.json',
    length: 22,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsObject',
    name: 'JS: Object',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-object.json',
    length: 37,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsPromise',
    name: 'JS: Promise',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-promise.json',
    length: 9,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsString',
    name: 'JS: String',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['JavaScript'],
    url: '/dicts/js-string.json',
    length: 32,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-builtin',
    name: 'Python: Built-in',
    description: 'Python Built-in API',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-builtin.json',
    length: 65,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-array',
    name: 'Python: array',
    description: 'Python array API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-array.json',
    length: 11,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-date',
    name: 'Python: date',
    description: 'Python date API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-date.json',
    length: 39,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-file',
    name: 'Python: file',
    description: 'Python file API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-file.json',
    length: 21,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-class',
    name: 'Python: class',
    description: 'Python class API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-class.json',
    length: 13,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-set',
    name: 'Python: set',
    description: 'Python set API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-set.json',
    length: 29,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-math',
    name: 'Python: math',
    description: 'Python math API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-math.json',
    length: 37,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-string',
    name: 'Python: string',
    description: 'Python string API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-string.json',
    length: 40,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-system',
    name: 'Python: system',
    description: 'Python system API ',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Python'],
    url: '/dicts/python-sys.json',
    length: 24,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javeArrayList',
    name: 'Java: ArrayList',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Java'],
    url: '/dicts/java-arraylist.json',
    length: 25,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaCharacter',
    name: 'Java: Character',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Java'],
    url: '/dicts/java-character.json',
    length: 8,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaHashmap',
    name: 'Java: Hashmap',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Java'],
    url: '/dicts/java-hashmap.json',
    length: 22,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaLinkedList',
    name: 'Java: LinkedList',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Java'],
    url: '/dicts/java-linkedlist.json',
    length: 25,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaString',
    name: 'Java: String',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Java'],
    url: '/dicts/java-string.json',
    length: 48,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaStringBuffer',
    name: 'Java: StringBuffer',
    description: 'JavaScript API t\u1EEB \u0111i\u1EC3n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Java'],
    url: '/dicts/java-stringBuffer.json',
    length: 20,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'linuxCommand',
    name: 'Linux',
    description: 'Linux Command',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Linux'],
    url: '/dicts/linux-command.json',
    length: 575,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'csharpKeywords',
    name: 'C#T\u1EEB kh\xF3a',
    description: 'C#T\u1EEB kh\xF3a v\xE0 c\xF4ng d\u1EE5ng c\u1EE7a ch\xFAng',
    category: 'L\u1EADp tr\xECnh',
    tags: ['C#'],
    url: '/dicts/csharp-keywords.json',
    length: 78,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'csharpString',
    name: 'C#: String API',
    description: 'C# String API',
    category: 'L\u1EADp tr\xECnh',
    tags: ['C#'],
    url: '/dicts/csharp-string.json',
    length: 79,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'csharpList',
    name: 'C#: List API',
    description: 'C# List API',
    category: 'L\u1EADp tr\xECnh',
    tags: ['C#'],
    url: '/dicts/csharp-list.json',
    length: 36,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'sql-lower-case',
    name: 'SQL: C\xE1c c\xE2u l\u1EC7nh th\u01B0\u1EDDng d\xF9ng lower case',
    description: 'SQL C\xE1c c\xE2u l\u1EC7nh th\u01B0\u1EDDng d\xF9ng ch\u1EEF th\u01B0\u1EDDng',
    category: 'L\u1EADp tr\xECnh',
    tags: ['SQL'],
    url: '/dicts/SQL_statement_lower-case.json',
    length: 12,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'sql-upper-case',
    name: 'SQL: C\xE1c c\xE2u l\u1EC7nh th\u01B0\u1EDDng d\xF9ng upper case',
    description: 'SQL C\xE1c c\xE2u l\u1EC7nh th\u01B0\u1EDDng d\xF9ng th\u1EE7 \u0111\xF4',
    category: 'L\u1EADp tr\xECnh',
    tags: ['SQL'],
    url: '/dicts/SQL_statement_upper-case.json',
    length: 12,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'ai-machine-learning',
    name: 'tr\xED tu\u1EC7 nh\xE2n t\u1EA1o: h\u1ECDc m\xE1y',
    description: 'AIh\u1ECDc m\xE1y Th\u01B0\u1EDDng \u0111\u01B0\u1EE3c s\u1EED d\u1EE5ngTi\u1EBFng Anht\u1EEB v\u1EF1ng',
    category: 'L\u1EADp tr\xECnh',
    tags: ['AI'],
    url: '/dicts/ai_machine_learning.json',
    length: 726,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'ai-ai-for-science',
    name: 'tr\xED tu\u1EC7 nh\xE2n t\u1EA1o: AI for Science',
    description: 'AI for Science Th\u01B0\u1EDDng \u0111\u01B0\u1EE3c s\u1EED d\u1EE5ngTi\u1EBFng Anht\u1EEB v\u1EF1ng',
    category: 'L\u1EADp tr\xECnh',
    tags: ['AI'],
    url: '/dicts/ai_for_science.json',
    length: 491,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'go_keyword',
    name: 'golang-keyword',
    description: 'got\u1EEB kh\xF3a ng\xF4n ng\u1EEF,',
    category: 'L\u1EADp tr\xECnh',
    tags: ['golang'],
    url: '/dicts/go_keyword.json',
    length: 25,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'go_builtin',
    name: 'golang-builtin',
    description: 'goCh\u1EE9c n\u0103ng t\xEDch h\u1EE3p ng\xF4n ng\u1EEFV\xE0ki\u1EC3u',
    category: 'L\u1EADp tr\xECnh',
    tags: ['golang'],
    url: '/dicts/go_builtin.json',
    length: 46,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustKeyword',
    name: 'Rust: Keyword',
    description: 'Rust T\u1EEB kh\xF3a',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Rust'],
    url: '/dicts/rust-keyword.json',
    length: 35,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustString',
    name: 'Rust: String',
    description: 'Rust C\xE1c ph\u01B0\u01A1ng th\u1EE9c ph\u1ED5 bi\u1EBFn ki\u1EC3u chu\u1ED7i th\u01B0 vi\u1EC7n chu\u1EA9n',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Rust'],
    url: '/dicts/rust-string.json',
    length: 24,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustVector',
    name: 'Rust: Vector',
    description: 'Rust M\u1EA3ng \u0111\u1ED9ng ki\u1EC3u b\u1ED9 s\u01B0u t\u1EADpVectorPh\u01B0\u01A1ng ph\xE1p ph\u1ED5 bi\u1EBFn',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Rust'],
    url: '/dicts/rust-vector.json',
    length: 28,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustHashMap',
    name: 'Rust: HashMap',
    description: 'Rust Lo\u1EA1i b\u1ED9 s\u01B0u t\u1EADpHashMapPh\u01B0\u01A1ng ph\xE1p ph\u1ED5 bi\u1EBFn',
    category: 'L\u1EADp tr\xECnh',
    tags: ['Rust'],
    url: '/dicts/rust-hashmap.json',
    length: 23,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'SoundSfxKey',
    name: 'AudioKey_UCS-SubCategory',
    description:
      'Hi\u1EC7u \u1EE9ng \xE2m thanh tr\xF2 ch\u01A1i th\u01B0\u1EDDng \u0111\u01B0\u1EE3c s\u1EED d\u1EE5ngt\u1EEB-UCS-SubCategory',
    category: 'L\u1EADp tr\xECnh',
    tags: ['RAZ'],
    url: '/dicts/AudioKey_SubCategory.json',
    length: 436,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SoundSfxKey2',
    name: 'AudioKey_UCS-Category',
    description:
      'Hi\u1EC7u \u1EE9ng \xE2m thanh tr\xF2 ch\u01A1i th\u01B0\u1EDDng \u0111\u01B0\u1EE3c s\u1EED d\u1EE5ngt\u1EEB-UCS-Category',
    category: 'L\u1EADp tr\xECnh',
    tags: ['RAZ'],
    url: '/dicts/AudioKey_Category.json',
    length: 82,
    language: 'code',
    languageCategory: 'code',
  },
]
const japaneseExam = [
  {
    id: 'japanese-hiragana',
    name: 'Hiragana',
    description: 'ch\u1EEF hiraganaluy\u1EC7n t\u1EADp',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n', 'Gojuon', 'Hiragana'],
    url: '/dicts/JapaneseHiragana.json',
    length: 280,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese-katakana',
    name: 'Katakana',
    description: 'Katakanaluy\u1EC7n t\u1EADp',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n', 'Gojuon', 'Katakana'],
    url: '/dicts/JapaneseKatakana.json',
    length: 280,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese001',
    name: 'nh\u1EEFng t\u1EEB th\xF4ng d\u1EE5ng c\u1EE7a ng\u01B0\u1EDDi Nh\u1EADt',
    description: 'Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Japanesebasicword.json',
    length: 100,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese001-zh',
    name: 'nh\u1EEFng t\u1EEB th\xF4ng d\u1EE5ng c\u1EE7a ng\u01B0\u1EDDi Nh\u1EADt',
    description: 'd\u1ECBch thu\u1EADt ti\u1EBFng trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Japanesebasicword_zh.json',
    length: 100,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese002',
    name: 'N5',
    description: 'Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N5.json',
    length: 670,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese002-zh',
    name: 'N5',
    description: 'd\u1ECBch thu\u1EADt ti\u1EBFng trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N5_zh.json',
    length: 670,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese003',
    name: 'N4',
    description: 'Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N4.json',
    length: 635,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese003-zh',
    name: 'N4',
    description: 'd\u1ECBch thu\u1EADt ti\u1EBFng trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N4_zh.json',
    length: 635,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese004',
    name: 'N3',
    description: 'Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N3.json',
    length: 1830,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese004-zh',
    name: 'N3',
    description: 'd\u1ECBch thu\u1EADt ti\u1EBFng trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N3_zh.json',
    length: 1830,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese005',
    name: 'N2',
    description: 'Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N2.json',
    length: 1836,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese005-zh',
    name: 'N2',
    description: 'd\u1ECBch thu\u1EADt ti\u1EBFng trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N2_zh.json',
    length: 1836,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese006',
    name: 'N1',
    description: 'Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N1.json',
    length: 3477,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese006-zh',
    name: 'N1',
    description: 'd\u1ECBch thu\u1EADt ti\u1EBFng trung',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/JapVocabList.N1_zh.json',
    length: 3477,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese007',
    name: 't\u1EA7n su\u1EA5t caot\u1EEB_N1',
    description: 't\u1EA7n su\u1EA5t caot\u1EEB_Ti\u1EBFng Nh\u1EADtN1',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N1.json',
    length: 3e3,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese008',
    name: 't\u1EA7n su\u1EA5t caot\u1EEB_N2',
    description: 't\u1EA7n su\u1EA5t caot\u1EEB_Ti\u1EBFng Nh\u1EADtN2',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N2.json',
    length: 2500,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese009',
    name: 't\u1EA7n su\u1EA5t caot\u1EEB_N3',
    description: 't\u1EA7n su\u1EA5t caot\u1EEB_Ti\u1EBFng Nh\u1EADtN3',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N3.json',
    length: 1999,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese0010',
    name: 't\u1EA7n su\u1EA5t caot\u1EEB_N4N5',
    description: 't\u1EA7n su\u1EA5t caot\u1EEB_Ti\u1EBFng Nh\u1EADtN4N5',
    category: 'Ti\u1EBFng Nh\u1EADt',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Jap_High-Frequency_N4N5.json',
    length: 2e3,
    language: 'romaji',
    languageCategory: 'ja',
  },
]
const germanExam = [
  {
    id: 'german2en',
    name: 'Ti\u1EBFng \u0110\u1EE9c B\u1EA3n d\u1ECBch Ti\u1EBFng Anh',
    description: 'Ti\u1EBFng \u0110\u1EE9ct\u1EEB v\u1EF1ng, Ti\u1EBFng Anhd\u1ECBch',
    category: 'Ti\u1EBFng \u0110\u1EE9c',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/german2en.json',
    length: 5892,
    language: 'de',
    languageCategory: 'de',
  },
  {
    id: 'en2german',
    name: 'Ti\u1EBFng Anh B\u1EA3n d\u1ECBch Ti\u1EBFng \u0110\u1EE9c',
    description: 'Ti\u1EBFng Anht\u1EEB v\u1EF1ng\uFF0CTi\u1EBFng \u0110\u1EE9cd\u1ECBch',
    category: 'Ti\u1EBFng \u0110\u1EE9c',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/en2german.json',
    length: 5025,
    language: 'en',
    languageCategory: 'de',
  },
]
const kazakhHapinDicts = [
  {
    id: 'kazakh_basic_3000_arabic_hapin',
    name: 'C\u0103n c\u1EE93000t\u1EEB(Phi\xEAn b\u1EA3n v\u0103n b\u1EA3n c\u0169)',
    description:
      'Kh\xE1i ni\u1EC7m c\u01A1 b\u1EA3n v\u1EC1 ti\u1EBFng Ti\u1EBFng Kazakhstan3000t\u1EEB(HapinPhi\xEAn b\u1EA3n v\u0103n b\u1EA3n c\u0169)',
    category: 'Ti\u1EBFng Kazakhstan',
    tags: ['C\u1ED5 v\u0103n', 'Hapin'],
    url: '/dicts/kazakh_basic_3000_arabic_hapin.json',
    length: 3002,
    language: 'hapin',
    languageCategory: 'kk',
  },
  {
    id: 'kazakh_basic_3000_cyrillic_hapin',
    name: 'C\u0103n c\u1EE93000t\u1EEB(phi\xEAn b\u1EA3n Cyrillic)',
    description: 'Kh\xE1i ni\u1EC7m c\u01A1 b\u1EA3n v\u1EC1 ti\u1EBFng Ti\u1EBFng Kazakhstan3000t\u1EEB(Hapinphi\xEAn b\u1EA3n Cyrillic)',
    category: 'Ti\u1EBFng Kazakhstan',
    tags: ['Cyrillic', 'Hapin'],
    url: '/dicts/kazakh_basic_3000_cyrillic_hapin.json',
    length: 3002,
    language: 'hapin',
    languageCategory: 'kk',
  },
]
const indonesianDicts = [
  {
    id: 'indonesian_highFrequency_3043',
    name: 'Ti\u1EBFng Indonesiat\u1EA7n su\u1EA5t caot\u1EEB v\u1EF1ng',
    description:
      'Ti\u1EBFng IndonesiaTh\u01B0\u1EDDng \u0111\u01B0\u1EE3c s\u1EED d\u1EE5ngt\u1EEBv\xE0 l\u1EDDi gi\u1EA3i th\xEDch c\u1EE7a Trung Qu\u1ED1c',
    category: 'Ti\u1EBFng Indonesia',
    tags: ['C\u01A1 b\u1EA3n'],
    url: '/dicts/Indonesian.json',
    length: 3037,
    language: 'id',
    languageCategory: 'id',
  },
]
const dictionaryResources = [
  ...chinaExam,
  ...internationalExam,
  ...childrenEnglish,
  ...programming,
  ...japaneseExam,
  ...germanExam,
  ...kazakhHapinDicts,
  ...indonesianDicts,
  // {
  //   id: 'zhtest',
  //   name: 'thi tiếng trung',
  //   description: 'thi tiếng trungtừ vựng',
  //   category: 'Bài kiểm tra',
  //   url: '/dicts/chinese_test.json',
  //   length: 27,
  //   language: 'zh',
  // },
  // {
  //   id: 'jptest',
  //   name: 'ngàybài kiểm tra tiểu luận',
  //   description: 'ngàybài kiểm tra tiểu luậntừ vựng',
  //   category: 'Bài kiểm tra',
  //   url: '/dicts/japanese_test.json',
  //   length: 20,
  //   language: 'ja',
  // },
]
const dictionaries = dictionaryResources.map((resource) => ({
  ...resource,
  chapterCount: (0, import_utils.calcChapterCount)(resource.length),
}))
const idDictionaryMap = Object.fromEntries(dictionaries.map((dict) => [dict.id, dict]))
