// kỳ thi trung quốc
const chinaExam = [
  {
    id: 'cet4',
    name: 'CET-4',
    description: 'Từ vựng Tiếng Anh Đại học (CET-4)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/CET4_T.json',
    length: 2607,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet6',
    name: 'CET-6',
    description: 'Từ vựng Tiếng Anh Đại học (CET-6)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/CET6_T.json',
    length: 2345,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'xinghuoqiaoji_4',
    name: 'CET-4 Cấp tốc',
    description: 'CET-4 Cấp tốc',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/xinghuoqiaoji_4.json',
    length: 2522,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'xinghuoqiaoji_6',
    name: 'CET-6 Cấp tốc',
    description: 'CET-6 Cấp tốc',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/xinghuoqiaoji_6.json',
    length: 7520,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet4-sub',
    name: 'CET-4 Cơ bản',
    description: 'CET-4 Rút gọn',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/DanCiDeJianFa_4.json',
    length: 1957,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'cet6-sub',
    name: 'CET-6 Cơ bản',
    description: 'CET-6 Rút gọn',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/DanCiDeJianFa_6.json',
    length: 1949,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyan',
    name: 'Thi Cao học',
    description: 'Từ vựng Tiếng Anh Thi Cao học',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/KaoYan_3_T.json',
    length: 3728,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyan_2024',
    name: 'Thi Cao học 2024',
    description: 'Từ vựng Tiếng Anh Thi Cao học 2024',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/KaoYan_2024.json',
    length: 3731,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyanshanguo_2023',
    name: 'Thi Cao học 2023',
    description: 'Từ vựng Tần suất Cao/Trung/Thấp 2023',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/KaoYanShanGuo_2023.json',
    length: 1771,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '926',
    name: 'Thi Cao học 926 từ vựng',
    description: '926 từ vựng cốt lõi',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/926.json',
    length: 926,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'dancimimi_1',
    name: 'Tiếng Anh bí mật 1',
    description: 'Từ vựng Tiếng Anh bí mật (1)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/DanCiDeMimi_1.json',
    length: 5657,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'dancimimi_2',
    name: 'Tiếng Anh bí mật 2',
    description: 'Từ vựng Tiếng Anh bí mật (2)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/DanCiDeMimi_2.json',
    length: 3827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2024HongBao T1',
    name: 'Sách Đỏ Tiếng Anh Cao Học 2024 (Phần 1)',
    description: 'Từ vựng bắt buộc Sách Đỏ Cao Học 2024 (Phần 1)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/2024HongBao_T1.json',
    length: 997,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2024HongBao T2',
    name: 'Sách Đỏ Tiếng Anh Cao Học 2024 (Phần 2)',
    description: 'Từ vựng bắt buộc Sách Đỏ Cao Học 2024 (Phần 2)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/2024HongBao_T2.json',
    length: 854,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Sách Đỏ-2026',
    name: 'Sách Đỏ Tiếng Anh Cao Học 2026',
    description: '2026 Thi Cao họctừ vựng (Từ vựng bắt buộc+Căn cứtừ+Nâng caotừ）',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/Sách Đỏ-2026.json',
    length: 4858,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'English_II',
    name: 'Tiếng Anhhaitừ vựng',
    description: 'Thi Cao học Tiếng Anhhaitừ vựng',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/English_II.json',
    length: 4559,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'kaoyanshanguo2025',
    name: 'Thi Cao học Shanguo 2025',
    description: 'Thi Cao học Shanguo 2025',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/kaoyanshanguo2025.json',
    length: 2257,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'level4',
    name: 'Tiếng Anh Chuyên ngành 4 (TEM-4)',
    description: 'Từ vựng Tiếng Anh Chuyên ngành 4',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/Level4luan_2_T.json',
    length: 4025,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'level8',
    name: 'Tiếng Anh Chuyên ngành 8 (TEM-8)',
    description: 'Từ vựng Tiếng Anh Chuyên ngành 8',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/Level8luan_2_T.json',
    length: 12197,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'archVocabulary',
    name: 'Tiếng Anh Kiến trúc',
    description: 'Từ vựng Tiếng Anh chuyên ngành Kiến trúc',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Chuyên ngành'],
    url: '/dicts/archVocabulary.json',
    length: 630,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'itVocabulary',
    name: 'Tiếng Anh CNTT',
    description: 'Đại học huyên ngành CNTTTiếng Anhtừ vựng',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Chuyên ngành'],
    url: '/dicts/itVocabulary.json',
    length: 1665,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'pets3',
    name: 'PETS',
    description: 'Từ vựng kì thi Tiếng Anh toàn quốc',
    category: 'Kỳ thi Trung Quốc',
    tags: ['PET'],
    url: '/dicts/PETS_3.json',
    length: 1942,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'pets3-2023',
    name: 'PETS 2023',
    description: 'Từ vựng kì thi Tiếng Anh toàn quốc',
    category: 'Kỳ thi Trung Quốc',
    tags: ['PET'],
    url: '/dicts/PETS3-2023.json',
    length: 4449,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English1',
    name: '1800 từ vựng tự học tần suất cao',
    description: '1800 từ vựng tự học tần suất cao',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tự học Tiếng Anh'],
    url: '/dicts/self-study_English1.json',
    length: 1800,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English2',
    name: 'Từ vựng Tiếng Anh tự học tần suất cao',
    description: 'Từ vựng Tiếng Anh tự học tần suất cao',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tự học Tiếng Anh'],
    url: '/dicts/self-study_English2.json',
    length: 2181,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'self-study_English3',
    name: 'tự họcTiếng Anhhaitrọntừ',
    description: 'Từ vựng Tiếng Anh Tự học 2 (Trọn bộ)',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tự học Tiếng Anh'],
    url: '/dicts/self-study_English3.json',
    length: 4603,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'coca_20000',
    name: 'COCA20000từ',
    description: 'COCA20000từ',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/coca20000.json',
    length: 20199,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words1',
    name: 'Essential Words',
    description: '4000 Essential English Words meaning',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/4000_Essential_English_Words-meaning.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '4000_Essential_English_Words2',
    name: 'Essential Words',
    description: '4000 Essential English Words sentence',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/4000_Essential_English_Words-sentence.json',
    length: 3600,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'longman_communication_3000_words',
    name: 'Longman Communication 3000',
    description: 'Most frequent words in both spoken and written English',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Longman_Communication_3000.json',
    length: 3168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_2000_English_Words',
    name: 'Top 2000 words',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/top2000words.json',
    length: 1867,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1500_nouns_Words',
    name: 'Top 1500 Nouns',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Top1500NounWords.json',
    length: 1525,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_1000_verb_Words',
    name: 'Top 1000 Verbs',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Top1000VerbWords.json',
    length: 1011,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_500_Adj_Words',
    name: 'Top 500 adj.',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Top500AdjectiveWords.json',
    length: 527,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_250_Adv_Words',
    name: 'Top 250 adv.',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Top250AdverbWords.json',
    length: 255,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_60_Pronouns',
    name: 'Top 60 pron.',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Top60Pronouns.json',
    length: 59,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'top_50_Prepositions',
    name: 'Top 50 prep.',
    description: 'with highest frequency',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Top50Prepositions.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'suffix word',
    name: 'suffix word',
    description: 'common suffix',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/suffix_word.json',
    length: 126,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'word roots1',
    name: 'word roots1',
    description: 'common roots',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/word_roots1.json',
    length: 369,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'adult self-study examination',
    name: 'Liên thông Đại họctừ vựng',
    description: 'Liên thông Đại họctừ vựng',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/adult-self-study-examination.json',
    length: 3692,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhuan-cha-ben-ying-yu',
    name: 'Chuyên tu Đại họcTiếng Anhtừ vựng',
    description: 'Chuyên tu Đại họcTiếng Anhtừ vựng',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/zhuan-cha-ben.json',
    length: 3217,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhuan-sheng-ben-xue-shi',
    name: 'Tiếng Anh Cử nhân',
    description: 'Tiếng Anh Cử nhân',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/xueshiyingyu.json',
    length: 897,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford5000từ',
    description: 'Oxford5000từ',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Merriam_Webster_sVocabularyBuilder',
    name: 'của WebsterTừ điển gốc từ',
    description: 'của WebsterTừ điển gốc từ',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Merriam_Webster_sVocabularyBuilder.json',
    length: 1191,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'tingshuokaoshi',
    name: 'Từ vựng Nghe hiểu Phổ biếntừ vựng',
    description: '16 chủ đề Nghe hiểu phổ biếntừHồi Tích',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/tingshuokaoshi.json',
    length: 557,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEFL_ZhangHongYan',
    name: 'Từ vựng TOEFL (ZhangHongYan)',
    description: 'Từ vựng TOEFL (ZhangHongYan) - Theo chủ đề',
    category: 'Kỳ thi Quốc tế',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_ZhangHongYan.json',
    length: 4032,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '2025KaoYanHongBaoShu',
    name: '2025Thi Cao học Tiếng Anhtừ vựnghongbaoSách',
    description: '2025Thi Cao học Tiếng Anhtừ vựnghongbaoSách',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Thi Cao học'],
    url: '/dicts/2025KaoYanHongBaoShu.json',
    length: 6705,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: '3000_ClassRoom_English_Words',
    name: 'Liên thông Đại học3000từ',
    description: 'Liên thông Đại họctừ vựng',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Tiếng Anh Đại học'],
    url: '/dicts/3000_ClassRoom_English_Words.json',
    length: 2991,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'frequently_used_words01',
    name: 'Từ vựng cấp tốc level 1',
    description: 'Từ vựng cấp tốc level 1',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/frequently_used_word01.json',
    length: 679,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'frequently_used_words03',
    name: 'Từ vựng cấp tốc level 2',
    description: 'Từ vựng cấp tốc level 2',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/frequently_used_word02.json',
    length: 1040,
    language: 'en',
    languageCategory: 'en',
  },

  {
    id: 'frequently_used_words03',
    name: 'Từ vựng cấp tốc level 3',
    description: 'Từ vựng cấp tốc level 3',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/frequently_used_word03.json',
    length: 1435,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'roger',
    name: "Roger's Words",
    description: 'Dùng trong học tập & công việcTiếng Anh',
    category: 'Từ điển Tiếng Anh',
    tags: ['Ngoại khoá'],
    url: '/dicts/RogersWords.json',
    length: 4174,
    language: 'en',
    languageCategory: 'en',
  },
]

// kỳ thi quốc tế
const internationalExam = [
  {
    id: 'pet-2024',
    name: 'PET-2024',
    description: 'CambridgeTiếng Anh - 2024',
    category: 'Kỳ thi Quốc tế',
    tags: ['PET'],
    url: '/dicts/pet-vacabulary-list-2024.json',
    length: 1871,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gmat',
    name: 'GMAT',
    description: 'GMAT từ vựng',
    category: 'Kỳ thi Quốc tế',
    tags: ['GMAT'],
    url: '/dicts/GMAT_3_T.json',
    length: 3047,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre',
    name: 'GRE',
    description: 'GRE từ vựng',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/GRE_3_T.json',
    length: 6515,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre1500',
    name: 'GREtập trung1500từ-fenanh trai',
    description: 'Từ vựng Tần suất cao GRE & TEM8',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/GRE_1500.json',
    length: 1533,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gre3000',
    name: 'GRE3000',
    description: 'Từ vựng GRE3000',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/GRE3000_3_T.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE-computer-based-test',
    name: 'GRETừ vựng trên máy tính vựng',
    description: 'GRETừ vựng trên máy tính vựng',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/GRE-computer-based-test.json',
    length: 1451,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ZaiYaoNiMing_GRE3000',
    name: 'GRE3000 Tái xuất',
    description: 'GRE3000 Tái xuấttừ vựng-cótừphiên bản mới của tình dục',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/ZaiYaoNiMing_GRE3000.json',
    length: 3041,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_equivalent',
    name: 'Từ đồng nghĩa GRE',
    description: 'Từ đồng nghĩa GRE',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/GRE_equivalent.json',
    length: 827,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'GRE_ciyileiji',
    name: 'GREtừTheo chủ đề',
    description: 'GREtừTheo chủ đề',
    category: 'Kỳ thi Quốc tế',
    tags: ['GRE'],
    url: '/dicts/gre-ciyileiji.json',
    length: 8785,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'biomedical-terms',
    name: 'Từ vựng Tiếng Anh Y sinh',
    description: 'Từ vựng Tiếng Anh Y sinh',
    category: 'Từ vựng chuyên ngành',
    tags: ['Sinh học'],
    url: '/dicts/BIOmedical.json',
    length: 560,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS_tinglichangjing',
    name: 'Chủ đề Nghe IELTStừ vựng',
    description: 'Chủ đề Nghe IELTStừ vựng',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_tinglichangjing.json',
    length: 1204,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_disorder',
    name: 'IELTSBản đầy đủ (Ngẫu nhiên)',
    description: 'IELTSBản đầy đủ (Ngẫu nhiên)',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_disorder.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts_order',
    name: 'IELTSBản đầy đủ (Theo thứ tự)',
    description: 'IELTSBản đầy đủ (Theo thứ tự)',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_order.json',
    length: 9389,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts',
    name: 'IELTS',
    description: 'IELTStừ vựng',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_3_T.json',
    length: 3575,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'heqiong',
    name: 'Từ vựng IELTS Listening (heQiong)từ vựng',
    description: 'Đề tổng hợp',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/HeQiong_IELTS.json',
    length: 2529,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang3',
    name: 'IELTS Wang C3',
    description: 'Danh từ riêng IELTS Listeningtừđề thi',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_3.json',
    length: 1135,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang4',
    name: 'IELTS Wang C4',
    description: 'Tính từ/Phó từ IELTS Listeningtừphótừđề thi',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_4.json',
    length: 346,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang5',
    name: 'IELTS Wang C5',
    description: 'Luyện tập nối âm và nuốt âm',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_5.json',
    length: 1569,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ieltsWang11',
    name: 'IELTS Wang C11',
    description: 'Đề tổng hợp',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_WANG_11.json',
    length: 1738,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'DuckCircle_IELTS',
    name: 'Từ vựng IELTS cốt lõi (Yaquan)từ',
    description: 'Từ vựng IELTS cốt lõi (Yaquan)từ',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/DuckCircle_IELTS.json',
    length: 2644,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSVocabularyBible',
    name: 'IELTStừHuizhen Jing',
    description: 'IELTStừHuizhen Jing',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTSVocabularyBible.json',
    length: 3673,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-807',
    name: 'IELTS wanglu 807',
    description: 'IELTS wanglu 807',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-807.json',
    length: 4340,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-high',
    name: 'IELTS real từ vựng tần suất cao',
    description: 'IELTS real từ vựng（tần suất caotừ vựng）',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-high.json',
    length: 524,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-5',
    name: 'IELTS real từ vựng 5',
    description: 'IELTS real từ vựng （5Tính thường xuyêntừHui và chuyển đổi tần suất）',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-5.json',
    length: 183,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-4',
    name: 'IELTS real từ vựng 4',
    description: 'IELTS real từ vựng （4Tính thường xuyêntừHui và chuyển đổi tần suất）',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-4.json',
    length: 201,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-3',
    name: 'IELTS real từ vựng 3',
    description: 'IELTS real từ vựng （3Tính thường xuyêntừHui và chuyển đổi tần suất）',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-3.json',
    length: 256,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-2',
    name: 'IELTS real từ vựng 2',
    description: 'IELTS real từ vựng （2Tính thường xuyêntừHui và chuyển đổi tần suất）',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-2.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ielts-real-1',
    name: 'IELTS real từ vựng 1',
    description: 'IELTS real từ vựng （1Tính thường xuyêntừHui và chuyển đổi tần suất）',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/ielts-real-1.json',
    length: 737,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS9988wangyong',
    name: 'IELTS9988wangyong',
    description: 'IELTS9988wangyong',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS9988wangyong.json',
    length: 3698,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSKingLu807',
    name: 'wanglu807IELTStừHuệ ThínhKHÔNG.2phiên bản',
    description: 'wanglu807IELTStừHuệ ThínhKHÔNG.2phiên bản',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTSKingLu807.json',
    length: 1916,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTSXDF7000',
    name: '100Nói xong câu7000IELTStừ',
    description: 'xdf 100Nói xong câu7000IELTStừ từTuyên bố trao đổi',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS_XDF_7000.json',
    length: 5567,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-oral-900',
    name: 'Nói IELTS 900 betaphiên bản',
    description: 'Nói IELTS 900 câu, nhu cầuhiện hữu qwerty cài đặtÂm trung nhỏTiếng Anhphông chữ',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-oral-900.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task1',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day1',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day1',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task1.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task2',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day2',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day2',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task2.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task3',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day3',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day3',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task3.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task4',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day4',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day4',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task4.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task5',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day5',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day5',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task5.json',
    length: 38,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task6',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day6',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day6',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task6.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task7',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day7',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day7',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task7.json',
    length: 39,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task8',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day8',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day8',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task8.json',
    length: 32,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task9',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day9',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day9',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task9.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task10',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day10',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day10',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task10.json',
    length: 44,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task11',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day11',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day11',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task11.json',
    length: 36,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task12',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day12',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day12',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task12.json',
    length: 45,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task13',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day13',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day13',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task13.json',
    length: 49,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task14',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day14',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day14',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task14.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task15',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day15',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day15',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task15.json',
    length: 29,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task16',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day16',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day16',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task16.json',
    length: 42,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task17',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day17',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day17',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task17.json',
    length: 22,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task18',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day18',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day18',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task18.json',
    length: 37,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-NeworientalDirect-Task19',
    name: 'xdfthính giác IELTS trung cấp cấp tốc day19',
    description: 'xdfthính giác IELTS trung cấp cấp tốc day19',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-NewOrientalDirect-Task19.json',
    length: 26,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-1',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day1',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day1',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day1.json',
    length: 74,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-2',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day2',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day2',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day2.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-3',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day3',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day3',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day3.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-4',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day4',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day4',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day4.json',
    length: 73,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-5',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day5',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day5',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day5.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-6',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day6',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day6',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day6.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-7',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day7',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day7',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day7.json',
    length: 75,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-8',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day8',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day8',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day8.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-9',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day9',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day9',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day9.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-10',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day10',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day10',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day10.json',
    length: 33,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-11',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day11',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day11',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day11.json',
    length: 52,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-12',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day12',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day12',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day12.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-13',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day13',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day13',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day13.json',
    length: 78,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-14',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day14',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day14',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day14.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-15',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day15',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day15',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day15.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-16',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day16',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day16',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day16.json',
    length: 77,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-17',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day17',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day17',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day17.json',
    length: 46,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'IELTS-listening-18-days-18',
    name: 'Luyện nghe IELTStừ vựng18bầu trời day18',
    description: 'Luyện nghe IELTStừ vựng18bầu trời day18',
    category: 'Kỳ thi Quốc tế',
    tags: ['IELTS'],
    url: '/dicts/IELTS-listening-18days-day18.json',
    length: 76,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'ket',
    name: 'KET',
    description: 'KET 2021từ',
    category: 'Kỳ thi Quốc tế',
    tags: ['KET'],
    url: './dicts/ket2021.json',
    length: 1147,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'sat',
    name: 'SAT',
    description: 'Hoa Kỳ SAT Từ vựng thi',
    category: 'Kỳ thi Quốc tế',
    tags: ['SAT'],
    url: '/dicts/SAT_3_T.json',
    length: 4464,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SATen',
    name: 'SAT en-en',
    description: 'SATYingying',
    category: 'Kỳ thi Quốc tế',
    tags: ['SAT'],
    url: '/dicts/SATen.json',
    length: 2681,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'toefl',
    name: 'TOEFL',
    description: 'Đề thi TOEFL phổ biếntừ',
    category: 'Kỳ thi Quốc tế',
    tags: ['TOEFL'],
    url: '/dicts/TOEFL_3_T.json',
    length: 4264,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'bec2',
    name: 'Tiếng Anh thương mại',
    description: 'Tiếng Anh thương mạichungtừ',
    category: 'Kỳ thi Quốc tế',
    tags: ['BEC'],
    url: '/dicts/BEC_2_T.json',
    length: 2753,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'bec3',
    name: 'BEC',
    description: 'BECCác kỳ thi chungtừ',
    category: 'Kỳ thi Quốc tế',
    tags: ['BEC'],
    url: '/dicts/BEC_3_T.json',
    length: 2825,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_junior',
    name: 'PTE Căn cứtừ vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_junior.json',
    length: 2651,
    language: 'en',
    languageCategory: 'en',
  },
  // {
  //   id: 'PTE_WFDgaopinci.json',
  //   name: 'PTE WFDtần suất caotừ vựng',
  //   description: 'WFDtần suất caotừchìm từ cao xuống thấp，sự thành thạo tối thiểu350cá nhân',
  //   category: 'Kỳ thi Quốc tế',
  //   tags: ['PTE'],
  //   url: '/dicts/PTE_WFDgaopinci.json',
  //   length: 1175,
  //   language: 'en',
  //   languageCategory: 'en',
  // },
  {
    id: 'PTE_senior',
    name: 'PTE Trình độ caotừ vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_senior.json',
    length: 3170,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_R_junior',
    name: 'đọc FIB Cơ học cơ bảntừ vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_R_junior.json',
    length: 941,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_R_senior',
    name: 'đọc FIB Máy móc tiên tiếntừ vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_R_senior.json',
    length: 1272,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_WFD',
    name: 'WFD Từ vựng trên máy tính vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_WFD.json',
    length: 1212,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_FIB_L',
    name: 'thính giác FIB Từ vựng trên máy tính vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_FIB_L.json',
    length: 646,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Basic_apeuni',
    name: 'PTE Căn cứtừ vựng xingji',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_Basic_apeuni.json',
    length: 2652,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Advanced_apeuni.json',
    name: 'PTE Trình độ caotừ vựng xingji',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_Advanced_apeuni.json',
    length: 3169,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Read_apeuni.json',
    name: 'PTE đọcFIBTừ vựng trên máy tính vựng xingji',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_Read_apeuni.json',
    length: 630,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'PTE_Listening_apeuni.json',
    name: 'PTE thính giácFIBTừ vựng trên máy tính vựng xingji',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/PTE_Listening_apeuni.json',
    length: 674,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'TOEIC',
    name: 'TOEIC từ vựng',
    description: '',
    category: 'Kỳ thi Quốc tế',
    tags: ['TOEIC'],
    url: '/dicts/TOEIC.json',
    length: 1694,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_B1',
    name: 'nhiềuphân loại hàng xómtừ vựngB1',
    description: 'nhiềuphân loại hàng xómtừ vựngB1',
    category: 'Kỳ thi Quốc tế',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_B1.json',
    length: 801,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_B2',
    name: 'nhiềuphân loại hàng xómtừ vựngB2',
    description: 'nhiềuphân loại hàng xómtừ vựngB2',
    category: 'Kỳ thi Quốc tế',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_B2.json',
    length: 1423,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Duolingo_Vocabulary_C1',
    name: 'nhiềuphân loại hàng xómtừ vựngC1',
    description: 'nhiềuphân loại hàng xómtừ vựngC1',
    category: 'Kỳ thi Quốc tế',
    tags: ['CEFR'],
    url: '/dicts/Duolingo_Vocabulary_C1.json',
    length: 1314,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford3000',
    name: 'Oxford3000từ',
    description: 'Oxford3000từ',
    category: 'Kỳ thi Quốc tế',
    tags: ['Phiên bản Oxford'],
    url: '/dicts/Oxford3000.json',
    length: 1342,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Oxford5000',
    name: 'Oxford5000từ',
    description: 'Oxford5000từ',
    category: 'Kỳ thi Quốc tế',
    tags: ['Phiên bản Oxford'],
    url: '/dicts/Oxford5000.json',
    length: 5836,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'voa',
    name: 'VOA Căn cứtừ vựng',
    description: 'VOA Căn cứtừ vựng',
    category: 'Kỳ thi Quốc tế',
    tags: ['Khác'],
    url: '/dicts/voa.json',
    length: 1505,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Common-Phrases-PTE-Unofficial',
    name: 'PTE Cụm từ thông dụng (không chính thức)',
    description: 'PTE Cụm từ thông dụng',
    category: 'Kỳ thi Quốc tế',
    tags: ['PTE'],
    url: '/dicts/Common-Phrases-PTE-Unofficial.json',
    length: 274,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Common-Phrases-FCE-Unofficial',
    name: 'FCE Cụm từ thông dụng (không chính thức)',
    description: 'FCE Cụm từ thông dụng',
    category: 'Kỳ thi Quốc tế',
    tags: ['FCE'],
    url: '/dicts/Common-Phrases-FCE-Unofficial.json',
    length: 438,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Categorized_TOEFL_Vocabulary_by_Zhanghongyan',
    name: 'Categorized Vocab.',
    description: 'từTheo chủ đề TOEFL 2021 by ZhangHongYan (sách gốc Nghĩa và ghi nhớ; từsự liên tiếpCon số)',
    category: 'Kỳ thi Quốc tế',
    tags: ['TOEFL'],
    url: '/dicts/Categorized_TOEFL_Vocabulary_by_Zhanghongyan.json',
    length: 4123,
    language: 'en',
    languageCategory: 'en',
  },
]

// màu xanh lámột vàiCon traiTiếng Anh
const childrenEnglish = [
  {
    id: 'gaokao3500',
    name: 'kỳ thi tuyển sinh đại học 3500 từ',
    description: 'Kỳ thi tuyển sinh đại học phổ thôngtừ 3500',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Cơ bản'],
    url: '/dicts/GaoKao_3500.json',
    length: 3893,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gaokaozhentihexin',
    name: 'Kỳ thi tuyển sinh đại học Câu hỏi thi trước đây Tần suất cao',
    description: 'Kỳ thi tuyển sinh đại học Câu hỏi thi trước đây Tần suất cao',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Cơ bản'],
    url: '/dicts/GaoKaoZhenTiHeXinGaoPin.json',
    length: 799,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'gaokao-yuedu-gaopin',
    name: 'kỳ thi tuyển sinh đại họcTiếng AnhĐọc tần suất caotừ vựng',
    description: 'kỳ thi tuyển sinh đại họcTiếng AnhĐọc tần suất caotừ vựng',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Cơ bản'],
    url: '/dicts/gaokao-yuedu-gaopin.json',
    length: 688,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'zhongkaohexin',
    name: 'Cốt lõi kỳ thi tuyển sinh trung họctừ',
    description: 'Cốt lõi kỳ thi tuyển sinh trung họctừ',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Cơ bản'],
    url: '/dicts/ZhongKaoHeXin.json',
    length: 2140,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce1',
    name: 'khái niệm mớiTiếng Anh-1',
    description: 'khái niệm mớiTiếng AnhKHÔNG.mộtsách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_1.json',
    length: 900,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce2',
    name: 'khái niệm mớiTiếng Anh-2',
    description: 'khái niệm mớiTiếng AnhKHÔNG.haisách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_2.json',
    length: 858,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce3',
    name: 'khái niệm mớiTiếng Anh-3',
    description: 'khái niệm mớiTiếng AnhKHÔNG.basách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_3.json',
    length: 1052,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce4',
    name: 'khái niệm mớiTiếng Anh-4',
    description: 'khái niệm mớiTiếng AnhKHÔNG.bốnsách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/NCE_4.json',
    length: 784,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-1',
    name: 'khái niệm mớiTiếng Anh(phiên bản mới)-1',
    description: 'khái niệm mớiTiếng Anhphiên bản mớiKHÔNG.mộtsách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-1.json',
    length: 908,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-2',
    name: 'khái niệm mớiTiếng Anh(phiên bản mới)-2',
    description: 'khái niệm mớiTiếng Anhphiên bản mớiKHÔNG.haisách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-2.json',
    length: 862,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-3',
    name: 'khái niệm mớiTiếng Anh(phiên bản mới)-3',
    description: 'khái niệm mớiTiếng Anhphiên bản mớiKHÔNG.basách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-3.json',
    length: 1062,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'nce-new-4',
    name: 'khái niệm mớiTiếng Anh(phiên bản mới)-4',
    description: 'khái niệm mớiTiếng Anhphiên bản mớiKHÔNG.bốnsách',
    category: 'Tiếng Anh Trẻ em',
    tags: ['New Concept English'],
    url: '/dicts/nce-new-4.json',
    length: 793,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SHjuniormiddleOxford',
    name: 'Trường trung học cơ sở Thượng Hải Oxfordtừ vựng',
    description: 'Trường trung học cơ sở Thượng Hải Oxfordtừ vựng',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Phiên bản Oxford'],
    url: '/dicts/OxfordVocabulary_juniorMiddleSH.json',
    length: 1270,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'BJJuniorHigh',
    name: 'Trường trung học cơ sở Bắc Kinh',
    description: 'Trường trung học cơ sở Bắc Kinh',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Khác'],
    url: '/dicts/beijing_junior_high_school.json',
    length: 1844,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel1',
    name: 'EF-LEVEL-1',
    description: 'EFcấp1',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_1.json',
    length: 297,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel2',
    name: 'EF-LEVEL-2',
    description: 'EFcấp2',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_2.json',
    length: 353,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel3',
    name: 'EF-LEVEL-3',
    description: 'EFcấp3',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_3.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel4',
    name: 'EF-LEVEL-4',
    description: 'EFcấp4',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_4.json',
    length: 178,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel5',
    name: 'EF-LEVEL-5',
    description: 'EFcấp5',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_5.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel6',
    name: 'EF-LEVEL-6',
    description: 'EFcấp6',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_6.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel7',
    name: 'EF-LEVEL-7',
    description: 'EFcấp7',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_7.json',
    length: 171,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel8',
    name: 'EF-LEVEL-8',
    description: 'EFcấp8',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_8.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel9',
    name: 'EF-LEVEL-9',
    description: 'EFcấp9',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_9.json',
    length: 165,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel10',
    name: 'EF-LEVEL-10',
    description: 'EFcấp10',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_10.json',
    length: 174,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel11',
    name: 'EF-LEVEL-11',
    description: 'EFcấp11',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_11.json',
    length: 176,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel12',
    name: 'EF-LEVEL-12',
    description: 'EFcấp12',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_12.json',
    length: 170,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel13',
    name: 'EF-LEVEL-13',
    description: 'EFcấp13',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_13.json',
    length: 172,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel14',
    name: 'EF-LEVEL-14',
    description: 'EFcấp14',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_14.json',
    length: 171,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel15',
    name: 'EF-LEVEL-15',
    description: 'EFcấp15',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_15.json',
    length: 168,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'eflevel16',
    name: 'EF-LEVEL-16',
    description: 'EFcấp16',
    category: 'Tiếng Anh Trẻ em',
    tags: ['EF'],
    url: '/dicts/EF_LEVEL_16.json',
    length: 170,
    language: 'en',
    languageCategory: 'en',
  },
  //Reading_Explorerloạt
  {
    id: 'ReadingExplorer3',
    name: 'Reading Explorer 3',
    description: 'từBảng trao đổi xuất phát từReading Explorer 3, Third Edition',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Khác'],
    url: '/dicts/ReadingExplorer3.json',
    length: 239,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Macmillan7000',
    name: 'macmillan7000',
    description: 'macmillan7000',
    category: 'Kỳ thi Trung Quốc',
    tags: ['Khác'],
    url: '/dicts/Macmillan7000.json',
    length: 6268,
    language: 'en',
    languageCategory: 'en',
  },
  // RAZ loạt
  {
    id: 'raz-AA',
    name: 'RAZ Đọc được xếp loại AA',
    description: 'RAZ Đọc được xếp loại AA',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-AA.json',
    length: 422,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-A',
    name: 'RAZ Đọc được xếp loại A',
    description: 'RAZ Đọc được xếp loại A',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-A.json',
    length: 487,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-B',
    name: 'RAZ Đọc được xếp loại B',
    description: 'RAZ Đọc được xếp loại B',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-B.json',
    length: 465,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-C',
    name: 'RAZ Đọc được xếp loại C',
    description: 'RAZ Đọc được xếp loại C',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-C.json',
    length: 480,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-D',
    name: 'RAZ Đọc được xếp loại D',
    description: 'RAZ Đọc được xếp loại D',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-D.json',
    length: 436,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-E',
    name: 'RAZ Đọc được xếp loại E',
    description: 'RAZ Đọc được xếp loại E',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-E.json',
    length: 427,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-F',
    name: 'RAZ Đọc được xếp loại F',
    description: 'RAZ Đọc được xếp loại F',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-F.json',
    length: 437,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-G',
    name: 'RAZ Đọc được xếp loại G',
    description: 'RAZ Đọc được xếp loại G',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-G.json',
    length: 435,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-H',
    name: 'RAZ Đọc được xếp loại H',
    description: 'RAZ Đọc được xếp loại H',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-H.json',
    length: 385,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-I',
    name: 'RAZ Đọc được xếp loại I',
    description: 'RAZ Đọc được xếp loại I',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-I.json',
    length: 408,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-J',
    name: 'RAZ Đọc được xếp loại J',
    description: 'RAZ Đọc được xếp loại J',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-J.json',
    length: 434,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-K',
    name: 'RAZ Đọc được xếp loại K',
    description: 'RAZ Đọc được xếp loại K',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-K.json',
    length: 397,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-L',
    name: 'RAZ Đọc được xếp loại L',
    description: 'RAZ Đọc được xếp loại L',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-L.json',
    length: 402,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-M',
    name: 'RAZ Đọc được xếp loại M',
    description: 'RAZ Đọc được xếp loại M',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-M.json',
    length: 403,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-N',
    name: 'RAZ Đọc được xếp loại N',
    description: 'RAZ Đọc được xếp loại N',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-N.json',
    length: 376,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-O',
    name: 'RAZ Đọc được xếp loại O',
    description: 'RAZ Đọc được xếp loại O',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-O.json',
    length: 429,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-P',
    name: 'RAZ Đọc được xếp loại P',
    description: 'RAZ Đọc được xếp loại P',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-P.json',
    length: 379,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Q',
    name: 'RAZ Đọc được xếp loại Q',
    description: 'RAZ Đọc được xếp loại Q',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-Q.json',
    length: 442,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-R',
    name: 'RAZ Đọc được xếp loại R',
    description: 'RAZ Đọc được xếp loại R',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-R.json',
    length: 422,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-S',
    name: 'RAZ Đọc được xếp loại S',
    description: 'RAZ Đọc được xếp loại S',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-S.json',
    length: 434,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-T',
    name: 'RAZ Đọc được xếp loại T',
    description: 'RAZ Đọc được xếp loại T',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-T.json',
    length: 427,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-U',
    name: 'RAZ Đọc được xếp loại U',
    description: 'RAZ Đọc được xếp loại U',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-U.json',
    length: 418,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-V',
    name: 'RAZ Đọc được xếp loại V',
    description: 'RAZ Đọc được xếp loại V',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-V.json',
    length: 409,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-W',
    name: 'RAZ Đọc được xếp loại W',
    description: 'RAZ Đọc được xếp loại W',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-W.json',
    length: 392,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-X',
    name: 'RAZ Đọc được xếp loại X',
    description: 'RAZ Đọc được xếp loại X',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-X.json',
    length: 546,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Y',
    name: 'RAZ Đọc được xếp loại Y',
    description: 'RAZ Đọc được xếp loại Y',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-Y.json',
    length: 461,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z',
    name: 'RAZ Đọc được xếp loại Z',
    description: 'RAZ Đọc được xếp loại Z',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z.json',
    length: 414,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z1',
    name: 'RAZ Đọc được xếp loại Z1',
    description: 'RAZ Đọc được xếp loại Z1',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z1.json',
    length: 467,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-Z2',
    name: 'RAZ Đọc được xếp loại Z2',
    description: 'RAZ Đọc được xếp loại Z2',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-Z2.json',
    length: 492,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'raz-all',
    name: 'RAZ Đọc được xếp loại tất cảtừ vựng',
    description: 'RAZ Đọc được xếp loại tất cảtừ vựng',
    category: 'Tiếng Anh Trẻ em',
    tags: ['RAZ'],
    url: '/dicts/raz-all.json',
    length: 5831,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'Cambridge_JOIN_IN',
    name: 'Trường tiểu học CambridgeTiếng Anh JOIN IN',
    description:
      'Nhà xuất bản nghiên cứu ngoại ngữVàNhà xuất bản Đại học Cambridge《giáo dục bắt buộcTiếng AnhTiêu chuẩn chương trình giảng dạy》nhu cầu đoàn thểvìTÔITrường tiểu họchọc sinhphát triểncủamộtbộTiếng AnhSách giáo khoa。',
    category: 'Tiếng Anh Trẻ em',
    tags: ['Khác'],
    url: '/dicts/Cambridge_JOIN_IN.json',
    length: 1350,
    language: 'en',
    languageCategory: 'en',
  },
]

// Từ điển lập trình
const programming = [
  {
    id: 'coder',
    name: 'Coder Dict',
    description: 'lập trình viênchungtừtừ vựng',
    category: 'Lập trình',
    tags: ['Cơ bản'],
    url: '/dicts/it-words.json',
    length: 1700,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'childCode',
    name: 'một vàiCon trai Python',
    description: 'một vàiCon trai Python chungtừ',
    category: 'Lập trình',
    tags: ['Lập trình trẻ em', 'Python'],
    url: '/dicts/Child_python_code.json',
    length: 19,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'childCode002',
    name: 'một vàiCon trai Python Turtle',
    description: 'một vàiCon trai Python Turtle chungtừ',
    category: 'Lập trình',
    tags: ['Lập trình trẻ em', 'Python'],
    url: '/dicts/Child_python_turtle_code.json',
    length: 27,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'childCode003',
    name: 'một vàiCon trai C++',
    description: 'một vàiCon trai C++ chungtừ',
    category: 'Lập trình',
    tags: ['Lập trình trẻ em', 'C++'],
    url: '/dicts/Child_cpp.json',
    length: 39,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'oi-xcpc',
    name: 'OI / XCPC cuộc thitừ vựng',
    description: 'OI / XCPC cuộc thitừ vựng',
    category: 'Lập trình',
    tags: ['C++'],
    url: '/dicts/OI_XCPC.json',
    length: 195,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'childCode004',
    name: 'Arduino',
    description: 'Arduinochungtừ',
    category: 'Lập trình',
    tags: ['Lập trình trẻ em', 'Arduino'],
    url: '/dicts/arduino_keywords.json',
    length: 78,
    language: 'en',
    languageCategory: 'code',
  },
  {
    id: 'jsArray',
    name: 'JS: Array',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-array.json',
    length: 36,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsDate',
    name: 'JS: Date',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-date.json',
    length: 34,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsGlobal',
    name: 'JS: Global',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-global.json',
    length: 9,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsMapSet',
    name: 'JS: Map & Set',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-map-set.json',
    length: 16,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsMath',
    name: 'JS: Math',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-math.json',
    length: 38,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsNumber',
    name: 'JS: Number',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-number.json',
    length: 22,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsObject',
    name: 'JS: Object',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-object.json',
    length: 37,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsPromise',
    name: 'JS: Promise',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-promise.json',
    length: 9,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'jsString',
    name: 'JS: String',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['JavaScript'],
    url: '/dicts/js-string.json',
    length: 32,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-builtin',
    name: 'Python: Built-in',
    description: 'Python Built-in API',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-builtin.json',
    length: 65,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-array',
    name: 'Python: array',
    description: 'Python array API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-array.json',
    length: 11,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-date',
    name: 'Python: date',
    description: 'Python date API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-date.json',
    length: 39,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-file',
    name: 'Python: file',
    description: 'Python file API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-file.json',
    length: 21,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-class',
    name: 'Python: class',
    description: 'Python class API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-class.json',
    length: 13,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-set',
    name: 'Python: set',
    description: 'Python set API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-set.json',
    length: 29,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-math',
    name: 'Python: math',
    description: 'Python math API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-math.json',
    length: 37,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-string',
    name: 'Python: string',
    description: 'Python string API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-string.json',
    length: 40,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'python-system',
    name: 'Python: system',
    description: 'Python system API ',
    category: 'Lập trình',
    tags: ['Python'],
    url: '/dicts/python-sys.json',
    length: 24,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javeArrayList',
    name: 'Java: ArrayList',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['Java'],
    url: '/dicts/java-arraylist.json',
    length: 25,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaCharacter',
    name: 'Java: Character',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['Java'],
    url: '/dicts/java-character.json',
    length: 8,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaHashmap',
    name: 'Java: Hashmap',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['Java'],
    url: '/dicts/java-hashmap.json',
    length: 22,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaLinkedList',
    name: 'Java: LinkedList',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['Java'],
    url: '/dicts/java-linkedlist.json',
    length: 25,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaString',
    name: 'Java: String',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['Java'],
    url: '/dicts/java-string.json',
    length: 48,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'javaStringBuffer',
    name: 'Java: StringBuffer',
    description: 'JavaScript API từ điển',
    category: 'Lập trình',
    tags: ['Java'],
    url: '/dicts/java-stringBuffer.json',
    length: 20,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'linuxCommand',
    name: 'Linux',
    description: 'Linux Command',
    category: 'Lập trình',
    tags: ['Linux'],
    url: '/dicts/linux-command.json',
    length: 575,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'csharpKeywords',
    name: 'C#Từ khóa',
    description: 'C#Từ khóa và công dụng của chúng',
    category: 'Lập trình',
    tags: ['C#'],
    url: '/dicts/csharp-keywords.json',
    length: 78,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'csharpString',
    name: 'C#: String API',
    description: 'C# String API',
    category: 'Lập trình',
    tags: ['C#'],
    url: '/dicts/csharp-string.json',
    length: 79,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'csharpList',
    name: 'C#: List API',
    description: 'C# List API',
    category: 'Lập trình',
    tags: ['C#'],
    url: '/dicts/csharp-list.json',
    length: 36,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'sql-lower-case',
    name: 'SQL: Các câu lệnh thường dùng lower case',
    description: 'SQL Các câu lệnh thường dùng chữ thường',
    category: 'Lập trình',
    tags: ['SQL'],
    url: '/dicts/SQL_statement_lower-case.json',
    length: 12,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'sql-upper-case',
    name: 'SQL: Các câu lệnh thường dùng upper case',
    description: 'SQL Các câu lệnh thường dùng thủ đô',
    category: 'Lập trình',
    tags: ['SQL'],
    url: '/dicts/SQL_statement_upper-case.json',
    length: 12,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'ai-machine-learning',
    name: 'trí tuệ nhân tạo: học máy',
    description: 'AIhọc máy Thường được sử dụngTiếng Anhtừ vựng',
    category: 'Lập trình',
    tags: ['AI'],
    url: '/dicts/ai_machine_learning.json',
    length: 726,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'ai-ai-for-science',
    name: 'trí tuệ nhân tạo: AI for Science',
    description: 'AI for Science Thường được sử dụngTiếng Anhtừ vựng',
    category: 'Lập trình',
    tags: ['AI'],
    url: '/dicts/ai_for_science.json',
    length: 491,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'go_keyword',
    name: 'golang-keyword',
    description: 'gotừ khóa ngôn ngữ,',
    category: 'Lập trình',
    tags: ['golang'],
    url: '/dicts/go_keyword.json',
    length: 25,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'go_builtin',
    name: 'golang-builtin',
    description: 'goChức năng tích hợp ngôn ngữVàkiểu',
    category: 'Lập trình',
    tags: ['golang'],
    url: '/dicts/go_builtin.json',
    length: 46,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustKeyword',
    name: 'Rust: Keyword',
    description: 'Rust Từ khóa',
    category: 'Lập trình',
    tags: ['Rust'],
    url: '/dicts/rust-keyword.json',
    length: 35,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustString',
    name: 'Rust: String',
    description: 'Rust Các phương thức phổ biến kiểu chuỗi thư viện chuẩn',
    category: 'Lập trình',
    tags: ['Rust'],
    url: '/dicts/rust-string.json',
    length: 24,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustVector',
    name: 'Rust: Vector',
    description: 'Rust Mảng động kiểu bộ sưu tậpVectorPhương pháp phổ biến',
    category: 'Lập trình',
    tags: ['Rust'],
    url: '/dicts/rust-vector.json',
    length: 28,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'rustHashMap',
    name: 'Rust: HashMap',
    description: 'Rust Loại bộ sưu tậpHashMapPhương pháp phổ biến',
    category: 'Lập trình',
    tags: ['Rust'],
    url: '/dicts/rust-hashmap.json',
    length: 23,
    language: 'code',
    languageCategory: 'code',
  },
  {
    id: 'SoundSfxKey',
    name: 'AudioKey_UCS-SubCategory',
    description: 'Hiệu ứng âm thanh trò chơi thường được sử dụngtừ-UCS-SubCategory',
    category: 'Lập trình',
    tags: ['RAZ'],
    url: '/dicts/AudioKey_SubCategory.json',
    length: 436,
    language: 'en',
    languageCategory: 'en',
  },
  {
    id: 'SoundSfxKey2',
    name: 'AudioKey_UCS-Category',
    description: 'Hiệu ứng âm thanh trò chơi thường được sử dụngtừ-UCS-Category',
    category: 'Lập trình',
    tags: ['RAZ'],
    url: '/dicts/AudioKey_Category.json',
    length: 82,
    language: 'code',
    languageCategory: 'code',
  },
]

// Tiếng Nhậttừ điển
const japaneseExam = [
  {
    id: 'japanese-hiragana',
    name: 'Hiragana',
    description: 'chữ hiraganaluyện tập',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản', 'Gojuon', 'Hiragana'],
    url: '/dicts/JapaneseHiragana.json',
    length: 280,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese-katakana',
    name: 'Katakana',
    description: 'Katakanaluyện tập',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản', 'Gojuon', 'Katakana'],
    url: '/dicts/JapaneseKatakana.json',
    length: 280,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese001',
    name: 'những từ thông dụng của người Nhật',
    description: 'Tiếng Anhdịch',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/Japanesebasicword.json',
    length: 100,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese001-zh',
    name: 'những từ thông dụng của người Nhật',
    description: 'dịch thuật tiếng trung',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/Japanesebasicword_zh.json',
    length: 100,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese002',
    name: 'N5',
    description: 'Tiếng Anhdịch',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N5.json',
    length: 670,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese002-zh',
    name: 'N5',
    description: 'dịch thuật tiếng trung',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N5_zh.json',
    length: 670,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese003',
    name: 'N4',
    description: 'Tiếng Anhdịch',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N4.json',
    length: 635,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese003-zh',
    name: 'N4',
    description: 'dịch thuật tiếng trung',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N4_zh.json',
    length: 635,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese004',
    name: 'N3',
    description: 'Tiếng Anhdịch',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N3.json',
    length: 1830,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese004-zh',
    name: 'N3',
    description: 'dịch thuật tiếng trung',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N3_zh.json',
    length: 1830,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese005',
    name: 'N2',
    description: 'Tiếng Anhdịch',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N2.json',
    length: 1836,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese005-zh',
    name: 'N2',
    description: 'dịch thuật tiếng trung',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N2_zh.json',
    length: 1836,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese006',
    name: 'N1',
    description: 'Tiếng Anhdịch',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N1.json',
    length: 3477,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese006-zh',
    name: 'N1',
    description: 'dịch thuật tiếng trung',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/JapVocabList.N1_zh.json',
    length: 3477,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese007',
    name: 'tần suất caotừ_N1',
    description: 'tần suất caotừ_Tiếng NhậtN1',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/Jap_High-Frequency_N1.json',
    length: 3000,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese008',
    name: 'tần suất caotừ_N2',
    description: 'tần suất caotừ_Tiếng NhậtN2',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/Jap_High-Frequency_N2.json',
    length: 2500,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese009',
    name: 'tần suất caotừ_N3',
    description: 'tần suất caotừ_Tiếng NhậtN3',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/Jap_High-Frequency_N3.json',
    length: 1999,
    language: 'romaji',
    languageCategory: 'ja',
  },
  {
    id: 'japanese0010',
    name: 'tần suất caotừ_N4N5',
    description: 'tần suất caotừ_Tiếng NhậtN4N5',
    category: 'Tiếng Nhật',
    tags: ['Cơ bản'],
    url: '/dicts/Jap_High-Frequency_N4N5.json',
    length: 2000,
    language: 'romaji',
    languageCategory: 'ja',
  },
]

// Tiếng Đứctừ điển
const germanExam = [
  {
    id: 'german2en',
    name: 'Tiếng Đức Bản dịch Tiếng Anh',
    description: 'Tiếng Đứctừ vựng, Tiếng Anhdịch',
    category: 'Tiếng Đức',
    tags: ['Cơ bản'],
    url: '/dicts/german2en.json',
    length: 5892,
    language: 'de',
    languageCategory: 'de',
  },
  {
    id: 'en2german',
    name: 'Tiếng Anh Bản dịch Tiếng Đức',
    description: 'Tiếng Anhtừ vựng，Tiếng Đứcdịch',
    category: 'Tiếng Đức',
    tags: ['Cơ bản'],
    url: '/dicts/en2german.json',
    length: 5025,
    language: 'en',
    languageCategory: 'de',
  },
]

// Tiếng KazakhstanHapintừ điển
const kazakhHapinDicts = [
  {
    id: 'kazakh_basic_3000_arabic_hapin',
    name: 'Căn cứ3000từ(Phiên bản văn bản cũ)',
    description: 'Khái niệm cơ bản về tiếng Tiếng Kazakhstan3000từ(HapinPhiên bản văn bản cũ)',
    category: 'Tiếng Kazakhstan',
    tags: ['Cổ văn', 'Hapin'],
    url: '/dicts/kazakh_basic_3000_arabic_hapin.json',
    length: 3002,
    language: 'hapin',
    languageCategory: 'kk',
  },
  {
    id: 'kazakh_basic_3000_cyrillic_hapin',
    name: 'Căn cứ3000từ(phiên bản Cyrillic)',
    description: 'Khái niệm cơ bản về tiếng Tiếng Kazakhstan3000từ(Hapinphiên bản Cyrillic)',
    category: 'Tiếng Kazakhstan',
    tags: ['Cyrillic', 'Hapin'],
    url: '/dicts/kazakh_basic_3000_cyrillic_hapin.json',
    length: 3002,
    language: 'hapin',
    languageCategory: 'kk',
  },
]

//Tiếng Indonesiatần suất caotừ vựng
const indonesianDicts = [
  {
    id: 'indonesian_highFrequency_3043',
    name: 'Tiếng Indonesiatần suất caotừ vựng',
    description: 'Tiếng IndonesiaThường được sử dụngtừvà lời giải thích của Trung Quốc',
    category: 'Tiếng Indonesia',
    tags: ['Cơ bản'],
    url: '/dicts/Indonesian.json',
    length: 3037,
    language: 'id',
    languageCategory: 'id',
  },
]

/**
 * Built-in dictionaries in an array.
 * Why arrays? Because it keeps the order across browsers.
 */
const dictionaryResources = [
  ...chinaExam,
  ...internationalExam,
  ...childrenEnglish,
  ...programming,
  ...japaneseExam,
  ...germanExam,
  ...kazakhHapinDicts,
  ...indonesianDicts,

  // {
  //   id: 'zhtest',
  //   name: 'thi tiếng trung',
  //   description: 'thi tiếng trungtừ vựng',
  //   category: 'Bài kiểm tra',
  //   url: '/dicts/chinese_test.json',
  //   length: 27,
  //   language: 'zh',
  // },
  // {
  //   id: 'jptest',
  //   name: 'ngàybài kiểm tra tiểu luận',
  //   description: 'ngàybài kiểm tra tiểu luậntừ vựng',
  //   category: 'Bài kiểm tra',
  //   url: '/dicts/japanese_test.json',
  //   length: 20,
  //   language: 'ja',
  // },
]

const dictionaries = dictionaryResources.map((resource) => ({
  ...resource,
  chapterCount: calcChapterCount(resource.length),
}))

/**
 * An object-map from dictionary IDs to dictionary themselves.
 */
const idDictionaryMap = Object.fromEntries(dictionaries.map((dict) => [dict.id, dict]))

const allDicts = [
  ...chinaExam,
  ...internationalExam,
  ...englishDict,
  ...professionalDict,
  ...childrenEnglish,
  ...codeDict,
  ...japaneseDict,
  ...germanDict,
  ...kzDict,
  ...idDict,
]

const englishDicts = allDicts.filter((d) => d.languageCategory === 'en')

const markdownTable =
  '# Danh sách chương trình tiếng Anh\n\n' +
  '| ID | Danh mục (Category) | Phân loại (Tags) | Tên chương trình | Mô tả | Số từ |\n' +
  '|---|---|---|---|---|---|\n' +
  englishDicts.map((d) => `| ${d.id} | ${d.category} | ${d.tags.join(', ')} | ${d.name} | ${d.description} | ${d.length} |`).join('\n')

fs.writeFileSync('/Users/macos/.gemini/antigravity-ide/brain/1dd73993-7fc2-4a9a-b639-7fa306c1fb20/english_dicts_report.md', markdownTable)
console.log('Report generated with ' + englishDicts.length + ' dictionaries.')
